---
title: "5.combined_long_omics_aim1"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
source("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/zachs_rerun/zc_functions.R") 
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(knitr, data.table, dplyr, tidyr, tableone, kableExtra, readxl,
               readr, car, RColorBrewer, gridExtra, mlbench, earth, ggplot2, 
               AppliedPredictiveModeling, caret, reshape2, corrplot, stringr,
               summarytools, grid, mice, plyr, mlmRev, cowplot, compositions,
               jtools, broom, patchwork, phyloseq, microbiome, glmnet, ISLR,
               MicrobiomeStat, ANCOMBC, ape, vegan, zCompositions, janitor,
               treeshap, Metrics, randomForest, xgboost, Ckmeans.1d.dp, caret,
               SHAPforxgboost, doParallel, parallel, tibble, Boruta)
```

```{r}
# Combined omic file
KO_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/merf_dfs/5.combined"
test <- read.csv(paste(KO_dir, "test_merged_all_omics_raw_meta.csv", sep = "/")) 
train <- read.csv(paste(KO_dir, "training_merged_all_omics_raw_meta.csv", sep = "/"))
```

```{r}
test <- test %>%
  dplyr::select(-which(grepl("unnamed", colnames(test), ignore.case = TRUE))) %>% 
  dplyr::select(-c(sample_id, subject_id, 
                              all_samples_x, all_samples_y, record_id, SampleID,
                              time_x, time_y, x_t, t, outcome_BMI_fnl_x,
                              outcome_BMI_fnl_y, outcome_BMI_fnl_merged_data, 
                              old_or_new, predicted_BL_BMI, differences_BL_BMI,
                              diff_BMI_quartile, diff_BMI_std, methyl_bmi_rs,
                              methyl_bmi_rs_standardized))

train <- train %>%
  dplyr::select(-which(grepl("unnamed", colnames(train), ignore.case = TRUE))) %>% 
  dplyr::select(-c(sample_id, subject_id, 
                               all_samples_x, all_samples_y, record_id, SampleID,
                               time_x, time_y, x_t, t, outcome_BMI_fnl_x,
                               outcome_BMI_fnl_y, outcome_BMI_fnl_merged_data, old_or_new,
                               predicted_BL_BMI, differences_BL_BMI, diff_BMI_quartile, 
                               diff_BMI_std, methyl_bmi_rs, methyl_bmi_rs_standardized))

```

```{r}
# Split test dataframe by "time"
test_0 <- test %>% dplyr::filter(time == 0)
test_6 <- test %>% dplyr::filter(time == 6)
test_12 <- test %>% dplyr::filter(time == 12)
m6_test <- test_6 %>% dplyr::select(c(outcome_BMI_fnl_test_long, all_samples))
m12_test <- test_12 %>% dplyr::select(c(outcome_BMI_fnl_test_long, all_samples))

# Split train dataframe by "time"
train_0 <- train %>% dplyr::filter(time == 0)
train_6 <- train %>% dplyr::filter(time == 6)
train_12 <- train %>% dplyr::filter(time == 12)
m6_train <- train_6 %>% dplyr::select(c(outcome_BMI_fnl_train_long, all_samples))
m12_train <- train_12 %>% dplyr::select(c(outcome_BMI_fnl_train_long, all_samples))

BL_6m_test <- merge(test_0, m6_test, by = "all_samples")
BL_12m_test <- merge(test_0, m12_test, by = "all_samples")
BL_6m_train <- merge(train_0, m6_train, by = "all_samples")
BL_12m_train <- merge(train_0, m12_train, by = "all_samples")

rm(train_0, train_6, train_12, m6_train, m12_train, 
   test_0, test_6, test_12, m6_test, m12_test)
```

```{r}
remove_cols <- c("Glucose", "all_samples", "outcome_BMI_fnl_train_long.y")
train_df <- BL_12m_train %>% dplyr::select(-remove_cols)

### Latent variables 
latent_variables <- c(
  "randomized_group", "bmi_prs", "cohort_number", "sex", "race", "age", 
  "HOMA_IR", "Insulin_endo", "HDL_Total_Direct_lipid",             
  "LDL_Calculated", "Triglyceride_lipid", "outcome_BMI_fnl_train_long.x")

# Check if all latent variables are still present in train_df
missing_columns <- setdiff(latent_variables, colnames(train_df))
if(length(missing_columns) > 0) {
  print(paste("Missing columns: ", paste(missing_columns, collapse = ", ")))
}

### Process DFs 
imputed <- preprocess_data(train_df, 
                           latent_variables, 
                           "medianImpute")
```


```{r}
set.seed(123)
train_control <- trainControl(method = "cv", number = 5, search = "grid")
# In[5] Regression Models ----
m6_results <- train_and_save_models(
  imputed,
  "outcome_BMI_fnl_train_long.x",
  train_control,
  "BL_all_omic_predicts_12m_bmi_regression")
```


```{r}
# describe the data
genus_ra_stats <- describe(train_df)
imputed_genus_ra_stats <- describe(imputed)

dev.new()
hist(genus_ra_stats$mean)
hist(imputed_genus_ra_stats$mean)

summary(genus_ra_stats$mean)
summary(imputed_genus_ra_stats$mean)

redundant_columns <- names(train_df)[
  sapply(train_df, function(col) mean(col == 0, na.rm = TRUE) > 0.8) |
    genus_ra_stats$mean == 0
]
```

```{r}
# remove all of the redundant columns that are in genus_df_imputed and species_df_imputed
remove <- c(redundant_columns)
genus_df_imputed_minus_redundant <- imputed %>%
                                    dplyr::select(-all_of(remove))

# retrain the models
genus_results <- train_and_save_models(
  genus_df_imputed_minus_redundant,
  "outcome_BMI_fnl_train_long.x",
  train_control,
  "BL_all_omic_predicts_12m_bmi_no_redundant_regression")
```


```{r}
###############################
###     Figure Analysis
###############################

# In[3]: Define base path and file paths ----
base_path <- "drift_fs/csv/results"

# Define file paths in a structured list
file_paths <- list(
  # genus
  m6_all_omic_g_ra_regression_beta = "BL_all_omic_predicts_12m_bmi_regression_beta.csv",
  m6_all_omic_g_ra_regression_feature_importance = "BL_all_omic_predicts_12m_bmi_regression_feature_importance.csv",
  m6_all_omic_g_ra_regression_metrics = "BL_all_omic_predicts_12m_bmi_regression_metrics.csv",
  # genus no redundant
  m6_all_omic_g_ra_regression_no_redundant_beta = "BL_all_omic_predicts_12m_bmi_no_redundant_regression_beta.csv",
  m6_all_omic_g_ra_regression_no_redundant_feature_importance = "BL_all_omic_predicts_12m_bmi_no_redundant_regression_feature_importance.csv",
  m6_all_omic_g_ra_regression_no_redundant_metrics = "BL_all_omic_predicts_12m_bmi_no_redundant_regression_metrics.csv"
)

# Read all data into a named list using lapply
data_list <- lapply(file_paths, 
                    function(path) read.csv(file.path(base_path, path)))

# Assign names to the data list based on the file paths
names(data_list) <- names(file_paths)

# In[4]: Process and plot for all datasets ----
datasets <- list(
  "m6_all_omics_Genus_ra" = list(
    beta = data_list$m6_all_omic_g_ra_regression_beta,
    feature_importance = data_list$m6_all_omic_g_ra_regression_feature_importance,
    metrics = data_list$m6_all_omic_g_ra_regression_metrics
  ),
  "m6_all_omics_Genus_ra_No_Redundant)" = list(
    beta = data_list$m6_all_omic_g_ra_regression_no_redundant_beta,
    feature_importance = data_list$m6_all_omic_g_ra_regression_no_redundant_feature_importance,
    metrics = data_list$m6_all_omic_g_ra_regression_no_redundant_metrics
  )
)

# In[5]: Now from the features, lets do a heatmap for the top 20 features ----
library(dplyr)
library(rlang)

get_top_n_features <- function(feature_importance, model_importance_column, n) {
  # Sort the dataframe by the importance column in descending order
  sorted_features <- feature_importance %>%
    arrange(desc(!!sym(model_importance_column)))  # Dynamically reference the importance column
  
  # Select the top N features
  top_features <- head(sorted_features, n)
  
  return(top_features)
}


get_top_n_features_all_models <- function(feature_importance, n = 20) {
  # Identify columns ending with '_Importance'
  importance_columns <- names(feature_importance)[grepl("_Importance$", names(feature_importance))]
  
  # Initialize a list to store results for each model
  top_features_list <- list()
  
  # Loop through each importance column and get top N features
  for (column in importance_columns) {
    model_name <- gsub("_Importance", "", column)  # Extract model name
    top_features_list[[model_name]] <- get_top_n_features(feature_importance, column, n)
  }
  return(top_features_list)
}


# Get top 20 features for one to test
top_20_features <- get_top_n_features_all_models(data_list$m6_all_omic_g_ra_regression_feature_importance, 20)
print(top_20_features)

top_20_features_no_r <- get_top_n_features_all_models(data_list$m6_all_omic_g_ra_regression_no_redundant_feature_importance, 20)
print(top_20_features_no_r)

# In[9]: Metric R ^ 2 for presentation ----

# lets get the testing R^2 for all the different datasets
# Function to extract metrics and calculate max R²
extract_metrics <- function(dataset_name, datasets) {
  metrics <- datasets[[dataset_name]]$metrics %>%
    dplyr::filter(DataType == "Test") %>%
    select(Model, R2)
  max_r2 <- max(metrics$R2, na.rm = TRUE)
  list(metrics = metrics, max_r2 = max_r2)
}

extract_metrics <- function(dataset) {
  if (is.null(dataset$metrics)) {
    stop("Metrics not found in the dataset.")
  }
  metrics <- dataset$metrics %>%
    dplyr::filter(DataType == "Test") %>%
    dplyr::select(Model, R2)
  max_r2 <- max(metrics$R2, na.rm = TRUE)
  list(metrics = metrics, max_r2 = max_r2)
}

m6_all_omics_Genus_ra = list(
  beta = data_list$m6_all_omic_g_ra_regression_beta,
  feature_importance = data_list$m6_all_omic_g_ra_regression_feature_importance,
  metrics = data_list$m6_all_omic_g_ra_regression_metrics)

m6_all_omics_Genus_ra_No_Redundant = list(
  beta = data_list$m6_all_omic_g_ra_regression_no_redundant_beta,
  feature_importance = data_list$m6_all_omic_g_ra_regression_no_redundant_feature_importance,
  metrics = data_list$m6_all_omic_g_ra_regression_no_redundant_metrics)

# Extract metrics and max R² for all datasets
results_all <- extract_metrics(m6_all_omics_Genus_ra)
results_allno_re <- extract_metrics(m6_all_omics_Genus_ra_No_Redundant)

# Calculate overall max R² for each main category
max_r2_genus <- results_all$max_r2
max_r2_genus_no_re <- results_allno_re$max_r2

# Calculate global max R² across all categories
max_r2 <- max(max_r2_genus, max_r2_genus_no_re)
max_r2 <- 0.5
# Prepare data and titles for genus
all_g_data_list <- list(results_all$metrics)
all_g_data_list_no_re <- list(results_allno_re$metrics)

# rename the models
all_g_data_list[[1]]$Model <- c("Lasso", "Ridge", "Elastic Net", "Random Forest", "XGBoost")
all_g_data_list_no_re[[1]]$Model <- c("Lasso", "Ridge", "Elastic Net", "Random Forest", "XGBoost")

genus_titles <- c("All BL omic and BMI 6m as dependent - Model Testing R²")
genus_titles_no_redundant <- c("All BL omic and BMI 6m as dependent Non Redundant - Model Testing R²")

# Generate combined genus plot
all_omic_plot_genus_ra <- create_plots(all_g_data_list, max_r2, genus_titles)
pdf("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/zachs_rerun/drift_fs/figures/m6/feb10_BL_all_omic_predicts_12m_bmi_regression.pdf", width = 7, height = 7)
print(all_omic_plot_genus_ra)
dev.off()

all_omic_plot_genus_ra_no_redundant <- create_plots(all_g_data_list_no_re, max_r2, genus_titles_no_redundant)
pdf("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/zachs_rerun/drift_fs/figures/m6/feb10_BL_all_omic_predicts_12m_bmi_no_redundant_regression.pdf", width = 7, height = 7)
print(all_omic_plot_genus_ra_no_redundant)
dev.off()

# In[10]: Plotting the top 5-10 features ----

# Extract top features from each dataset
extract_top_features <- function(dataset, top_n = 15) {
  # Extract columns ending with '_Importance'
  importance_columns <- grep("_Importance$", names(dataset$feature_importance), value = TRUE)
  
  # Check if importance columns exist
  if (length(importance_columns) == 0) {
    stop("No columns ending with '_Importance' found in feature_importance.")
  }
  
  # Get a column with the total importance
  dataset$feature_importance <- dataset$feature_importance %>%
    dplyr::mutate(Total_Importance = rowSums(dataset$feature_importance[, importance_columns], na.rm = TRUE))
  
  # Sort by total importance from high to low
  dataset$feature_importance <- dataset$feature_importance %>%
    dplyr::arrange(desc(Total_Importance))
  
  # Get the top n features
  top_features <- dataset$feature_importance %>%
    dplyr::select(Variable, Total_Importance) %>%
    head(top_n)
  
  # Remove the total importance column and return top n features
  dataset$feature_importance <- dataset$feature_importance %>%
    dplyr::select(-Total_Importance) %>%
    head(top_n)
  
  return(dataset$feature_importance)
}


all_omic_genus_features <- extract_top_features(datasets$m6_all_omics_Genus_ra)
all_omic_genus_no_rendundant_features <- extract_top_features(datasets$m6_all_omics_Genus_ra_No_Redundant) 


# rename the column names
colnames(all_omic_genus_features) <- c("Variable", "Random Forest", "Lasso", 
                                       "Ridge", "Elastic Net",  "XGBoost")

colnames(all_omic_genus_no_rendundant_features) <- c("Variable", "Random Forest", 
                                                     "Lasso", "Ridge", 
                                                     "Elastic Net",  "XGBoost")

all_omic_genus_features <- all_omic_genus_features %>%
  mutate(
    Variable = case_when(
      Variable == "Leptin_6m" ~ "Leptin",
      Variable == "score_std" ~ "Genetic BMI risk score",
      Variable == "HOMA_IR_6m" ~ "Homeostasis Model Assessment",
      Variable == "avg_systolic_6m" ~ "Average Systolic Blood Pressure",
      Variable == "Insulin_endo_6m" ~ "Insulin",
      TRUE ~ Variable))

all_omic_genus_no_rendundant_features <- all_omic_genus_no_rendundant_features %>%
  mutate(
    Variable = case_when(
      Variable == "Leptin_6m" ~ "Leptin",
      Variable == "score_std" ~ "Genetic BMI risk score",
      Variable == "HOMA_IR_6m" ~ "Homeostasis Model Assessment",
      Variable == "avg_systolic_6m" ~ "Average Systolic Blood Pressure",
      Variable == "Insulin_endo_6m" ~ "Insulin",
      TRUE ~ Variable))

# Create and save plots for each dataset
create_feature_plot(
  all_omic_genus_features,
  "Top 10 Features - BL omics predicts 6m BMI",
  "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/zachs_rerun/drift_fs/figures/m6/feb10_all_omic_predicts_m12BMI_feature_plot.pdf")

create_feature_plot(
  all_omic_genus_no_rendundant_features,
  "Top 10 Features - Non Redundant BL omics predicts 6m BMI",
  "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/zachs_rerun/drift_fs/figures/m6/feb10_all_omic_predicts_m12BMI_feature_plot_no_redundant.pdf")
```