---
title: "Paper plots for render clinical plus"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE)
```

## LOAD 

```{r include=FALSE}
rm(list = ls())
#source("zc_functions.R") 
#install.packages("rsq")  
library(pacman)
p_load(tools, reticulate, viridis, tidyplots, patchwork, jsonlite, maps, ggvenn, 
       caret, caretEnsemble, glmnet, xgboost, ggplot2, glmmLasso, corrplot,
       readr, plyr, dplyr, tidyr, purrr, tibble, stringr, psych, randomForest,  
       reshape2, scales, gridExtra, plotly, sf, tidyverse, naniar, VIM, gridExtra,
       sjPlot, htmltools, officer, flextable, webshot, apaTables, MuMIn, lme4, 
       glue, grid, rsq, pheatmap, GGally, VennDiagram, glmmTMB, broom.mixed, gt)
#library(nlme)

'%ni%' <- Negate('%in%')
r2_general <-function(preds,actual){ 
  return(1- sum((preds - actual) ^ 2)/sum((actual - mean(actual))^2))
}
q_squared <- function(actual, predicted) {
  ss_res <- sum((actual - predicted)^2)
  ss_tot <- sum((actual - mean(actual))^2)
  1 - (ss_res / ss_tot)
}

# ANOVA & Feat Imp Comparisons 
omic_out_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/april/anova_results/plots/paper_render/basic_plus_diet/"
venn_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/april/anova_results/plots/venn/"
# MERF LONG 
#predict_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/april/final_merf_dfs"
#pred_dir_long <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/april/new_split"
pred_dir_long <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/may_basic_plus/long"
#merf_long <- read.csv('/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/april/anova_results/new_split/april_long_predictions_df_april29.csv') %>% 
merf_long <- read.csv('/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/may_basic_plus/long/merf_long_predictions_df.csv') %>%  
             dplyr::filter(Model == "MSE Model")

basic <- read.csv(file.path(pred_dir_long, "basic_long.csv")) %>% dplyr::rename(y_new_basic = y_hat_new)
meta <- read.csv(file.path(pred_dir_long, "meta_keep_long.csv")) %>% dplyr::rename(y_new_meta = y_hat_new)
grs <- read.csv(file.path(pred_dir_long, "only_grs_long.csv")) %>% dplyr::rename(y_new_grs = y_hat_new)
taxa <- read.csv(file.path(pred_dir_long, "only_taxa_long.csv")) %>% dplyr::rename(y_new_taxa = y_hat_new)
pathway <- read.csv(file.path(pred_dir_long, "only_pathway_long.csv")) %>% dplyr::rename(y_new_pathway = y_hat_new)
micom <- read.csv(file.path(pred_dir_long, "only_micom_long.csv")) %>% dplyr::rename(y_new_micom = y_hat_new)
metabo <- read.csv(file.path(pred_dir_long, "only_metabo_long.csv")) %>% dplyr::rename(y_new_metabo = y_hat_new)
all <- read.csv(file.path(pred_dir_long, "only_all_long.csv")) %>% dplyr::rename(y_new_all = y_hat_new)

# MERF DELTA
merf_delta <- read.csv('/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/may_basic_plus/delta/merf_delta_predictions_df.csv') %>% 
              dplyr::filter(Model == "MSE Model")
predict_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/merf_python/may_basic_plus/"
basic_md <- read.csv(file.path(predict_dir, "basic_delta_april29.csv")) %>% dplyr::rename(y_new_basic = y_hat_new)
meta_md <- read.csv(file.path(predict_dir, "meta_keep_delta_april29.csv")) %>% dplyr::rename(y_new_meta = y_hat_new)
grs_md <- read.csv(file.path(predict_dir, "only_grs_delta_april29.csv")) %>% dplyr::rename(y_new_grs = y_hat_new)
taxa_md <- read.csv(file.path(predict_dir, "only_taxa_delta_april29.csv")) %>% dplyr::rename(y_new_taxa = y_hat_new)
pathway_md <- read.csv(file.path(predict_dir, "only_pathway_delta_april29.csv")) %>% dplyr::rename(y_new_pathway = y_hat_new)
micom_md <- read.csv(file.path(predict_dir, "only_micom_delta_april29.csv")) %>% dplyr::rename(y_new_micom = y_hat_new)
metabo_md <- read.csv(file.path(predict_dir, "only_metabo_delta_april29.csv")) %>% dplyr::rename(y_new_metabo = y_hat_new)
all_md <- read.csv(file.path(predict_dir, "only_all_delta_april29.csv")) %>% dplyr::rename(y_new_all = y_hat_new)

# GLMMLASSO LONG
#gl_lasso_long <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/march30_long/new_split_may/april_long_predictions_df_april29.csv") %>% 
gl_lasso_long <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/june_lasso_long_predictions_df.csv") %>%
   dplyr::rename(y_new_meta = y_new_meta_only,
                 y_new_grs = y_new_grs_only,
                 y_new_taxa = y_new_tax_only,
                 y_new_micom = y_new_micom_only,
                 y_new_pathway = y_new_path_only,
                 y_new_metabo = y_new_metabo_only,
                 y_new_all = y_new_all_only)

gl_ftimp_long_basic <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_plusbasic_gl_long_top_features.csv")
gl_ftimp_long_meta <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_plusmeta_gl_long_top_features.csv")
gl_ftimp_long_grs <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/grs_gl_long_top_features.csv")
gl_ftimp_long_taxa <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_plustaxa_gl_long_top_features.csv")
gl_ftimp_long_micom <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_plusmicom_gl_long_top_features.csv")
gl_ftimp_long_pathway <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_pluspathway_gl_long_top_features.csv")
gl_ftimp_long_metabo <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_plusmetabo_gl_long_top_features.csv")
gl_ftimp_long_all <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/long/may_basic_plusall_gl_long_top_features.csv")

# GLMMLASSO DELTA 
gl_lasso_delta <- read.csv('/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/gl_delta_predictions_df.csv') %>% 
   dplyr::rename(y_new_basic = y_new_basic_only,
                 y_new_meta = y_new_meta_only,
                 y_new_grs = y_new_grs_only,
                 y_new_taxa = y_new_tax_only,
                 y_new_micom = y_new_micom_only,
                 y_new_pathway = y_new_path_only,
                 y_new_metabo = y_new_metab_only,
                 y_new_all = y_new_all_only)

gl_ftimp_delta_basic <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/basic_gl_delta_top_features.csv")
gl_ftimp_delta_meta <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/meta_gl_delta_top_features.csv")
gl_ftimp_delta_grs <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/grs_gl_delta_top_features.csv")
gl_ftimp_delta_taxa <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/taxa_gl_delta_top_features.csv")
gl_ftimp_delta_micom <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/micom_gl_delta_top_features.csv")
gl_ftimp_delta_pathway <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/pathway_gl_delta_top_features.csv")
gl_ftimp_delta_metabo <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/metabo_gl_delta_top_features.csv")
gl_ftimp_delta_all <- read.csv("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/play_scripts/2.models/glmmlasso/may_basic_plus/delta/all_gl_delta_top_features.csv")
```

# Rename top 20 features 

```{r}
gl_ftimp_delta_meta <- gl_ftimp_delta_meta %>%
  dplyr::mutate(
    Feature = dplyr::recode(
      Feature,
      "Ldl" = "LDL",
      "Randomized group1" = "IMF Diet Grp.",
      "Sex" = "Sex (Male)",
      "Hdl" = "HDL",
      "Glucose" = "Glucose x",
      "Homo ir" = "Homo-IR"))

gl_ftimp_delta_pathway <- gl_ftimp_delta_pathway %>%
  dplyr::mutate(
    Feature = dplyr::recode(
      Feature,
      "Superpathway of sulfolactate degradation" = "Sulfolactate degr.",
                "Superpathway of l phenylalanine biosynthesis" = "L-Phe biosynthesis",
                "Urate biosynthesis inosine 5  Phosphate degradation" = "Urate-IMP pathway",
                "Isoprene biosynthesis ii Engineered" = "Isoprene biosynth. II",
                "Mixed acid fermentation" = "Mixed acid ferm.",
                "Tca cycle vii Acetate producers" = "TCA VII (acetate)",
                "Hexitol fermentation to lactate Formate Ethanol and acetate" = "Hexitol → Lac/For/Eth/Ace",
                "Superpathway of R r Butanediol biosynthesis" = "(R,R)-Butanediol biosynth.",
                "Heme biosynthesis ii Anaerobic" = "Heme biosynth. II (anaerobic)"))

gl_ftimp_delta_metabo <- gl_ftimp_delta_metabo %>%
  dplyr::mutate(
    Feature = dplyr::recode(
      Feature,
      "Ldl" = "LDL",
      "Glyca" = "Glycoprotein acetyls",
      "Vldl size" = "VLDL-size",
      "Hdl size" = "HDL-size",
      "Gly" = "Glycine",
      "Vldl tg" = "TGs in VLDL",
      "Tg by pg" = "TGs/Phosphoglycerides",
      "Dha pct" = "DHA (% of FAs)",
      "Vldl l" = "Lipids in VLDL"))

gl_ftimp_delta_all <- gl_ftimp_delta_all %>%
  dplyr::mutate(
    Feature = dplyr::recode(
      Feature,
      "Superpathway of sulfolactate degradation" = "Sulfolactate degr.",
      "Superpathway of l phenylalanine biosynthesis" = "L-Phe biosynthesis",
      "Ldl" = "LDL",
      "Glyca" = "Glycoprotein acetyls",
      "Vldl size" = "VLDL-size",
      "Hdl size" = "HDL-size",
      "Gly" = "Glycine",
      "Vldl tg" = "TGs in VLDL",
      "Tg by pg" = "TGs/Phosphoglycerides",
      "Dha pct" = "DHA (% of FAs)",
      "Vldl l" = "Lipids in VLDL"))

gl_ftimp_long_meta <- gl_ftimp_long_meta %>%
  dplyr::mutate(
    Feature = dplyr::recode(
      Feature,
      "Ldl" = "LDL",
      "Randomized group1" = "IMF Diet Grp.",
      "Sex" = "Sex (Male)",
      "Hdl" = "HDL",
      "Glucose" = "Glucose x",
      "Homo ir" = "Homo-IR"))

gl_ftimp_long_metabo <- gl_ftimp_long_metabo %>%
  dplyr::mutate(
    Feature = dplyr::recode(
      Feature,
      "Ldl" = "LDL",
      "Glyca" = "Glycoprotein acetyls",
      "Bohbutyrate" = "3-Hydroxybutyrate",
      "Ldl size" = "LDL-size",
      "Hdl size" = "HDL-size",
      "Gly" = "Glycine",
      "Gln" = "Glutamine",
      "Vldl tg" = "TGs in VLDL",
      "Tg by pg" = "TGs/Phosphoglycerides",
      "Dha pct" = "DHA (% of FAs)",
      "Vldl l" = "Lipids in VLDL"))
```

# Merf feature conversions
```{r}
library(jsonlite)
library(purrr)
library(dplyr)

# Define a renaming dictionary
feature_rename_metabo <- c(
  "GlycA" = "Glycoprotein acetyls",
  "DHA_pct" = "DHA (% of FAs)",
  "Gly" = "Glycine",
  "Ala" = "Alanine",
  "Glucose.y" = "Glucose",
  "Gln" = "Glutamine-IR",
  "HDL_CE" = "Chol. esters in HDL",
  "DHA_pct" = "DHA (% of FAs)",
  "IDL_CE_pct" = "",
  "PUFA_pct" = "PUFA (%)",
  "HDL_size" = "HDL-size",
  "VLDL_TG" = "TGs in VLDL")

feature_rename_metabo_lg <- c(
  "GlycA" = "Glycoprotein acetyls",
  "DHA_pct" = "DHA (% of FAs)",
  "Gly" = "Glycine",
  "Ala" = "Alanine",
  "Glucose.y" = "Glucose",
  "Gln" = "Glutamine-IR",
  "HDL_CE" = "Chol. esters in HDL",
  "DHA_pct" = "DHA (% of FAs)",
  "IDL_CE_pct" = "",
  "PUFA_pct" = "PUFA (%)",
  "HDL_size" = "HDL-size",
  "VLDL_TG" = "TGs in VLDL",
  "Acetoacetate.x" = "Acetoacetate")

feature_rename_meta <- c(
  "Triglyceride_lipid" = "TG",
  "HDL_Total_Direct_lipid" = "HDL",
  "LDL_Calculated" = "LDL",
  "Glucose.x" = "Glucose",
  "Insulin_endo" = "Insulin",
  "HOMA_IR" = "Homo-IR",
  "race" = "Race",
  "age" = "Age",
  "sex" = "Sex (Male)",
  "randomized_group" = "IMF Diet Grp.")

feature_rename_taxa <- c(
  "g__Anaerobutyricum" = "G Anaerobutyricum",
  "g__Anaerotignum_189125" = "G Anaerotignum 189125",
  "g__CAG-127" = "G CAG-127",
  "g__Clostridium_Q_135822" = "G Clostridium Q 135822",
  "g__Collinsella" = "G Collinsella",
  "g__Coprenecus" = "G Coprenecus",
  "g__Dorea_A" = "G Dorea A",
  "g__Enterocloster" = "G Enterocloster",
  "g__Eubacterium_I" = "G Eubacterium I",
  "g__Faecalibacillus" = "G Faecalibacillus",
  "g__Faecousia" = "G Faecousia",
  "g__Frisingicoccus" = "G Frisingicoccus",
  "g__Haemophilus_D_735815" = "G Haemophilus D 735815",
  "g__Holdemanella" = "G Holdemanella",
  "g__Lawsonibacter" = "G Lawsonibacter")

feature_rename_taxa_lg <- c(
  "g__Acetatifactor" = "G Acetatifactor",
  "g__Agathobacter_164117" = "G Agathobacter 164117",
  "g__Agathobaculum" = "G Agathobaculum",
  "g__Akkermansia" = "G Akkermansia",
  "g__Alistipes_A_871400" = "G Alistipes A 871400",
  "g__BX12" = "G BX12",
  "g__Bifidobacterium_388775" = "G Bifidobacterium 388775",
  "g__CAG-127" = "G CAG-127",
  "g__CAG-274" = "G CAG-274",
  "g__Clostridium_Q_135822" = "G Clostridium Q 135822",
  "g__Collinsella" = "G Collinsella",
  "g__Coprococcus_A_187866" = "G Coprococcus A 187866",
  "g__Copromonas" = "G Copromonas",
  "g__Eggerthella" = "G Eggerthella",
  "g__Eisenbergiella" = "G Eisenbergiella")

feature_rename_pathway <- c(
  "D.glucarate.degradation.I" = "D-glucarate degr. ",
  "L.lysine.biosynthesis.II" = "L-lysine biosyn. II",
  "L.lysine.fermentation.to.acetate.and.butanoate" = "Lys ferm. to acetate/butanoate",
  "L.rhamnose.degradation.I" = "L-rhamnose degr. I",
  "TCA.cycle.VI..obligate.autotrophs. " = "TCA VI (autotrophs)",
  "aromatic.biogenic.amine.degradation..bacteria." = "Aromatic amine degr. (bacteria)",
  "glucose.and.glucose.1.phosphate.degradation" = "Glucose/G1P degr.",
  "incomplete.reductive.TCA.cycle" = "Incomplete reductive TCA",
  "isoprene.biosynthesis.II..engineered." = "Isoprene biosynth. II (eng.)",
  "isopropanol.biosynthesis" = "Isopropanol biosyn.")

feature_rename_pathway_lg <- c(
  "D.glucarate.degradation.I" = "D-glucarate degr. ",
  "L.lysine.biosynthesis.II" = "L-lysine biosyn. II",
  "L.lysine.fermentation.to.acetate.and.butanoate" = "Lys ferm. to acetate/butanoate",
  "L.rhamnose.degradation.I" = "L-rhamnose degr. I",
  "TCA.cycle.VI..obligate.autotrophs. " = "TCA VI (autotrophs)",
  "aromatic.biogenic.amine.degradation..bacteria." = "Aromatic amine degr. (bacteria)",
  "glucose.and.glucose.1.phosphate.degradation" = "Glucose/G1P degr.",
  "incomplete.reductive.TCA.cycle" = "Incomplete reductive TCA",
  "isoprene.biosynthesis.II..engineered." = "Isoprene biosynth. II (eng.)",
  "isopropanol.biosynthesis" = "Isopropanol biosyn.",
  "Bifidobacterium.shunt" = "Bifidobacterium shunt",
  "GDP.mannose.biosynthesis" = "GDP mannose biosyn.",
  "L.histidine.degradation.I" = "L-hist. degr.I ",
  "UDP.2.3.diacetamido.2.3.dideoxy..alpha..D.mannuronate.biosynthesis" = "UDP-DDDA-ManA biosyn.",
  "X1.4.dihydroxy.6.naphthoate.biosynthesis.I " = "1,4 dihydroxy naphthoate biosyn.I",
  "X1.4.dihydroxy.6.naphthoate.biosynthesis.II" = "1,4 dihydroxy naphthoate biosyn.II",
  "allantoin.degradation.to.glyoxylate.III" = "Allantoin → Glyoxylate III",
  "arginine..ornithine.and.proline.interconversion" = "Arg–Orn–Pro interconversion",
  "glycolysis.V..Pyrococcus." = "Glycolysis V Pyro.",
  "heme.biosynthesis.II..anaerobic." = "heme biosyn.II anaerobic",
  "lactose.and.galactose.degradation.I" = "lactose/galactose degr.I",
  "pyrimidine.deoxyribonucleotides.de.novo.biosynthesis.II" = "Pyr dNTP biosyn.II",
  "reductive.acetyl.coenzyme.A.pathway" = "Red. Acetyl-CoA Pathway",
  "superpathway.of.histidine..purine..and.pyrimidine.biosynthesis" = "His. Purine & Pyrimidine Biosyn.",
  "superpathway.of.pyridoxal.5..phosphate.biosynthesis.and.salvage" = "Pyridoxal-5-phosphate Biosyn. & Salvage",
  "purine.nucleotides.degradation.II..aerobic." = "Aerobic Purine Degradation II aerobic.",
  "superpathway.of.L.methionine.biosynthesis..by.sulfhydrylation." = "Sulfhydrylation -> L-methionine Biosyn.",
  "myo.inositol.degradation.I" = "Myo-inositol Degradation I"
  )

feature_rename_all <- c(
  "Dephospho.CoA" = "Dephospho-CoA",
  "GlycA" = "Glycoprotein acetyls",
  "DHA_pct" = "DHA (% of FAs)",
  "Gly" = "Glycine",
  "Ala" = "Alanine",
  "Glucose.y" = "Glucose",
  "Gln" = "Glutamine-IR",
  "X3.methoxy.acetaminophen" = "3-Methoxy Acetaminophen",
  "DHA_pct" = "DHA (% of FAs)",
  "aldehydo.D.xylose" = "Ald. D-xylose",
  "PUFA_pct" = "PUFA (%)",
  "VLDL_size" = "VLDL-size",
  "L.fucose" = "L-fucose",
  "Thiamin.monophosphate" = "Thiamin monophos.",
  "Insulin_endo" = "Insulin",
  "HOMA_IR" = "Homo-IR",
  "MUFA_pct" = "MUFA (% of FAs)",
  "LA" = "Linoleic acid", 
  "Omega_6" = "Omega6 FA",
  "TCA.cycle.VI..obligate.autotrophs." = "TCA VI (autotrophs)",
  "g__Acetatifactor" = "G Acetatifactor",
  "indole.3.acetate" = "Indole-3-acetate"
  )

```


```{r}
# Renaming function
rename_features_in_json <- function(json_str, feature_rename_map) {
  # Fix the invalid JSON format by replacing single quotes with double quotes
  json_str <- gsub("'", "\"", json_str)
  
  # Parse the fixed JSON string into a list
  feature_list <- jsonlite::fromJSON(json_str, simplifyDataFrame = FALSE)
  
  # Rename each feature if it's in the mapping
  renamed_list <- lapply(feature_list, function(item) {
    original_name <- item$Feature
    if (original_name %in% names(feature_rename_map)) {
      item$Feature <- feature_rename_map[[original_name]]
    }
    item
  })
  
  # Convert back to JSON
  toJSON(renamed_list, auto_unbox = TRUE)
}
```


```{r}
# Apply to the column MERF Long
meta <- meta %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_meta)))
metabo <- metabo %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_metabo_lg)))
taxa <- taxa %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_taxa_lg)))
pathway <- pathway %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_pathway_lg)))
all <- all %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_all)))
# Apply to the column MERF Delta
meta_md <- meta_md %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_meta)))
metabo_md <- metabo_md %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_metabo)))
taxa_md <- taxa_md %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_taxa)))
pathway_md <- pathway_md %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_pathway)))
all_md <- all_md %>%
  mutate(Top_15_Feature_Importances = map_chr(Top_15_Feature_Importances, 
                                              ~rename_features_in_json(.x, feature_rename_all)))
```

################################################################################

# DO we see and improvement in the omics upon clinical models

```{r}
omic_dfs <- list(
  merf_long = merf_long,
  gl_lasso_long = gl_lasso_long,
  merf_delta = merf_delta, 
  gl_lasso_delta = gl_lasso_delta)

omic_name_labels <- c(
  "merf_long"      = "MERF Longitudinal BMI",
  "gl_lasso_long"  = "GlmmLasso Longitudinal BMI",
  "merf_delta"     = "MERF BMI Changes (Deltas)",
  "gl_lasso_delta" = "GlmmLasso BMI Changes (Deltas)")

for (omic_name in names(omic_dfs)) {
  omic <- omic_dfs[[omic_name]]
  
  ### ANOVA 
  mod_dat <- omic
  lmer_basic_b <- lmer(bmi ~ y_new_basic + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_basic_meta_b <- lmer(bmi ~ y_new_basic + y_new_meta + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_b <- lmer(bmi ~ y_new_meta + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_grs <- lmer(bmi ~ y_new_meta + y_new_grs  + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_micom <- lmer(bmi ~ y_new_meta + y_new_micom  + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_pathway <- lmer(bmi ~ y_new_meta + y_new_pathway + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_taxa <- lmer(bmi ~ y_new_meta + y_new_taxa + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_metabo <- lmer(bmi ~ y_new_meta + y_new_metabo + (1|Cluster), data = mod_dat, REML = FALSE)
  lmer_meta_all <- lmer(bmi ~ y_new_meta + y_new_all + (1|Cluster), data = mod_dat, REML = FALSE)
  
  # Put your models into a named list
  models <- list(
    `Clinical`  = lmer_meta_b,
    `Clinical + GRS`  = lmer_meta_grs,
    `Clinical + Micom` = lmer_meta_micom,
    `Clinical + Pathway` = lmer_meta_pathway,
    `Clinical + Taxa`    = lmer_meta_taxa,
    `Clinical + Metabo`  = lmer_meta_metabo,
    `Clinical + All` = lmer_meta_all)
  
  # Extract R2 values for each model
  r2_df_clin_plus <- do.call(rbind, lapply(names(models), function(name) {
    r2_vals_clin_plus <- r.squaredGLMM(models[[name]])
    data.frame(Model = name,
      R2m = r2_vals_clin_plus[1, "R2m"],
      R2c = r2_vals_clin_plus[1, "R2c"])
  }))
  #print(r2_df)
  assign(paste0(omic_name, "_r2_df"), r2_df_clin_plus)
  
  lmer_models <- list(
    c("lmer_meta_b", "lmer_meta_grs"),
    c("lmer_meta_b", "lmer_meta_taxa"),
    c("lmer_meta_b", "lmer_meta_micom"),
    c("lmer_meta_b", "lmer_meta_pathway"),
    c("lmer_meta_b", "lmer_meta_metabo"),
    c("lmer_meta_b", "lmer_meta_all"))
  
  lmer_models_clin_p <- list()  # empty list to store ANOVA results
  all_anova_tables_clin_p <- list()
  for (model_pair in lmer_models) {
    model_1 <- get(model_pair[1])
    model_2 <- get(model_pair[2])
    anova_out_clin_p <- anova(model_1, model_2)  # lmerMod objects
    # tidied_result <- tidy(anova_result)
    anova_out_clin_p$model_comparison <- paste(model_pair[1], "vs", model_pair[2])
    lmer_models_clin_p[[length(lmer_models_clin_p) + 1]] <- anova_out_clin_p
  }
  # Combine all results into one dataframe
  anova_table_clin_p <- do.call(rbind, lmer_models_clin_p)
  anova_table_clean_clin_p <- anova_table_clin_p %>%
    dplyr::filter(!is.na(`Chisq`) & !is.na(`Pr(>Chisq)`)) %>%
    dplyr::mutate(across(where(is.numeric), round, 3)) %>% 
    dplyr::select(-c("npar")) 
  rownames(anova_table_clean_clin_p) <- NULL

  # Extract model names for reference
  anova_table_clean_clin_p$model_1 <- gsub(" vs .*", "", anova_table_clean_clin_p$model_comparison)
  anova_table_clean_clin_p$model_2 <- gsub(".* vs ", "", anova_table_clean_clin_p$model_comparison)
  
  # Annotate significance and select relevant columns only
  anova_labels_clin_p <- anova_table_clean_clin_p %>%
  dplyr::mutate(
    Compared_Model = dplyr::recode(
       model_comparison,
       #"lmer_basic_b vs lmer_basic_meta_b" = "Clinical",
       "lmer_meta_b vs lmer_meta_grs" = "Clinical + GRS",
       "lmer_meta_b vs lmer_meta_taxa" = "Clinical + Taxa",
       "lmer_meta_b vs lmer_meta_micom" = "Clinical + Micom",
       "lmer_meta_b vs lmer_meta_pathway" = "Clinical + Pathway",
       "lmer_meta_b vs lmer_meta_metabo" = "Clinical + Metabo",
       "lmer_meta_b vs lmer_meta_all" = "Clinical + All"
    ),
    Significance = case_when(
      `Pr(>Chisq)` < 0.001 ~ "***",
      `Pr(>Chisq)` < 0.01  ~ "**",
      `Pr(>Chisq)` < 0.05  ~ "*",
      TRUE            ~ ""
    ),
    `Pr(>Chisq)` = case_when(
      `Pr(>Chisq)` < 0.001 ~ "<0.001",
      `Pr(>Chisq)` < 0.01  ~ "<0.01",
      TRUE ~ as.character(`Pr(>Chisq)`)
    )
  ) %>%
  dplyr::select(Compared_Model, AIC, `Pr(>Chisq)`, Significance)
  
  # Apply the custom order to your data #START HERE ####
  custom_order_clin_plus <- c("Clinical", 
                              "Clinical + GRS",
                              "Clinical + Pathway", 
                              "Clinical + Taxa",
                              "Clinical + Micom", 
                              "Clinical + Metabo", 
                              "Clinical + All")
  
  r2_annotated_clin_plus <- r2_df_clin_plus %>%
                            left_join(anova_labels_clin_p, 
                                      by = c("Model" = "Compared_Model")) %>%
                            dplyr::mutate(Model = factor(Model, 
                                 levels = custom_order_clin_plus)) %>%
                                 arrange(Model)
  
  basic_r2 <- r2_annotated_clin_plus$R2m[r2_annotated_clin_plus$Model == "Clinical"]
  sig_plot_clin_plus <- ggplot(r2_annotated_clin_plus, 
                     aes(x = Model, y = R2m, fill = Model)) +
    geom_col(width = 0.7) +
    geom_text(aes(y = R2m + 0.036, label = Significance), size = 8) +
    geom_hline(yintercept = basic_r2, linetype = "dashed", color = "black") +
    scale_y_continuous(limits = c(0, 0.72),
                       expand = expansion(mult = c(0, 0.1))) +
    scale_fill_manual(values = c(
      "Clinical + All"      = "#b44241",
      "Clinical + Metabo"   = "#C76374",
      "Clinical + Micom"    = "#996759",
      "Clinical + Pathway"  = "#D8A39D",
      "Clinical + Taxa"     = "#8B3A3A",
      "Clinical + GRS"      = "#E18476",
      "Clinical"            = "#fecdc7")) +
    labs(title = glue("R² {omic_name_labels[[omic_name]]}"),
      x = "Model Comparisons",
      y = expression(R^2*" = Fixed Effect Variance")) +
    theme_minimal(base_size = 14) +
    theme(legend.position = "none",
          plot.margin = ggplot2::margin(t = 2, r = 2, b = 2, l = 2, unit = "cm"),
      axis.text.y = element_text(face = "bold", hjust = 1, size = 14),
      axis.text.x = element_text(face = "bold", size = 14, hjust = 1, angle = 45),
      axis.title.x = element_text(margin = ggplot2::margin(0.5,0,0,0, unit = "cm"), size = 14),
      axis.title.y = element_text(margin = ggplot2::margin(0,0.8,0,0, unit = "cm"), size = 14))
  #sig_plot
  assign(paste0(omic_name, "_sig_plot_clin_plus"), sig_plot_clin_plus)
  
  for_table <- r2_annotated_clin_plus %>% 
               dplyr::select(-c(R2c)) %>% 
               rename("R²*" = R2m, 
                      "P-Value" = `Pr(>Chisq)`)
                      #"Chisq Statistic" = Chisq)
  
  final_anova_table_clin_p <- for_table %>% gt() %>%
    tab_header(title = "Model Comparison (ANOVA)") %>%
    fmt_number(columns = where(is.numeric), decimals = 2) %>%
    sub_missing(missing_text = "-") %>%
    cols_width(1 ~ pct(20),
               `R²*` ~ pct(15), 
              # Df ~ pct(8),
              #`Chisq Statistic` ~ pct(15), 
              Significance ~ pct(15),
              `P-Value` ~ pct(15), 
              AIC ~ pct(11), 
              Significance ~ pct(11)) %>%
    cols_align(align = "center",
      columns = everything()) %>% 
    cols_align("left", columns = Model) %>%
    tab_options(table.width = pct(60),
                table.align = "center") %>%
    opt_table_font(font = list(
        google_font("Arial"),   # fallback to system font if unavailable
        default_fonts())) %>%
  # Style body text
  tab_style(
    style = cell_text(size = 14),
    locations = cells_body()
  ) %>%
  # Style column labels
  tab_style(
    style = cell_text(size = 16, weight = "bold"),
    locations = cells_column_labels()
  ) %>%
  # Style title
  tab_style(
    style = cell_text(size = 18, weight = "bold"),
    locations = cells_title()
  )
  assign(paste0(omic_name, "_anova_table_clin_p"), final_anova_table_clin_p)
}

# Assuming you saved the cleaned data frames *before* turning them into gt tables:
all_anova_clean_tables_clin_p <- list(
  merf_long    = merf_long_anova_table_clin_p,
  gl_lasso_long = gl_lasso_long_anova_table_clin_p,
  merf_delta    = merf_delta_anova_table_clin_p,
  gl_lasso_delta = gl_lasso_delta_anova_table_clin_p)

raw_tables_clin_p <- lapply(all_anova_clean_tables_clin_p, 
                            function(gt_obj) gt_obj[["_data"]])

combined_anova_df_clin_p <- bind_rows(
  lapply(names(raw_tables_clin_p), function(name) {
    df <- raw_tables_clin_p[[name]]
    df$Model_Type <- name
    df
    }),
  .id = "Source"
)

# Step 1: Prepare and clean data
combined_anova_df_clin_p <- combined_anova_df_clin_p %>%
  dplyr::mutate(Model_Type = case_when(
    Model_Type == "merf_long"      ~ "D. MERF (Longitudinal BMI prediction)",
    Model_Type == "gl_lasso_long"  ~ "B. GlmmLasso (Longitudinal BMI Prediction)",
    Model_Type == "merf_delta"     ~ "C. MERF (Change in BMI (Delta) Prediction)",
    Model_Type == "gl_lasso_delta" ~ "A. GlmmLasso (Change in BMI (Delta) Prediction)",
    TRUE ~ Model_Type
  ))

table_data_clin_p <- combined_anova_df_clin_p %>%
  dplyr::select(-Source) %>%
  arrange(Model_Type) %>%
  dplyr::mutate(across(where(is.numeric), ~ round(.x, 3))) %>%
  dplyr::select(-Model_Type)

# Step 2: Split by model type
tables_clin_p <- split(table_data_clin_p, combined_anova_df_clin_p$Model_Type)

# Step 3: Create title + table stacked using cowplot
table_grobs_clin_p <- lapply(names(tables_clin_p), function(name) {
  
  # Title as a ggdraw object
  title_grob_clin_p <- cowplot::ggdraw() +
    cowplot::draw_label(name, fontface = "bold", 
                        size = 14, hjust = 0.5,
                        fontfamily = "Arial") #+
    #theme(plot.margin = ggplot2::margin(0, 0, 0.1, 0))  # space below title
  # Table as a ggdraw object
  table_clin_p <- ggtexttable(tables_clin_p[[name]], 
                       theme = ttheme("classic"), rows = NULL)
  table_grob_clin_p <- cowplot::ggdraw(table_clin_p)
  # Combine title and table vertically
  cowplot::plot_grid(title_grob_clin_p, table_grob_clin_p, 
                     ncol = 1, 
                     rel_heights = c(0.1, 1))
})
# Step 4: Arrange all tables into a grid
final_plot_clin_p <- cowplot::plot_grid(plotlist = table_grobs_clin_p, 
                                 ncol = 2, rel_widths = c(1, 1))

# Show plot
print(final_plot_clin_p)
ggsave(paste0(omic_out_dir, "anova_clinical_combined.png"), final_plot_clin_p, 
       width = 30, height = 20, dpi = 300, bg = 'white')


# Combined ANOVA table
final_anova_table_clin_p2 <- combined_anova_df_clin_p %>% 
  dplyr::select(-c("Source")) %>% 
  mutate(Model_Type = dplyr::case_when(
    Model_Type == "merf_long" ~ "MERF (Longitudinal BMI prediction)",
    Model_Type == "gl_lasso_long" ~ "GlmmLasso (Longitudinal BMI Prediction)",
    Model_Type == "merf_delta" ~ "MERF (Change in BMI (Delta) Prediction)",
    Model_Type == "gl_lasso_delta" ~ "GlmmLasso (Change in BMI (Delta) Prediction)",
    TRUE ~ Model_Type
  )) %>% 
  gt(groupname_col = "Model_Type") %>%
    tab_header(title = "Additive Model Comparison's (ANOVA)") %>%
    fmt_number(columns = where(is.numeric), decimals = 3) %>%
    #fmt_number(columns = "Df", decimals = 0) %>% 
    sub_missing(missing_text = "-") %>%
    cols_width(1 ~ pct(16),
               `R²*` ~ pct(10), 
               #Df ~ pct(12),
               #`Chisq Statistic` ~ pct(12), 
               Significance ~ pct(10),
               `P-Value` ~ pct(10), 
               AIC ~ pct(10), 
               Model_Type ~ pct(12)) %>%
    cols_align(align = "center",
      columns = everything()) %>% 
    cols_align("left", columns = Model) %>%
    tab_options(table.width = pct(90),
                table.align = "center") %>%
    opt_table_font(font = list(
        google_font("Arial"),   # fallback to system font if unavailable
        default_fonts())) %>%
    tab_style(style = cell_text(weight = "bold"),
              locations = cells_column_labels()) %>% 
  tab_style(style = list(
    cell_fill(color = "lightgray"),
    cell_text(weight = "bold",
              size = 12)),
  locations = cells_row_groups())

#final_anova_table_clin_p2
gtsave(final_anova_table_clin_p, filename = paste0(omic_out_dir, "anova_table_clin_p.png"))
```


# Figure x : Combined ANOVA R2 plots for clinical combined 

```{r echo=FALSE, fig.width = 10, fig.asp = 1.05, out.width="95%", warning=FALSE}
# Combine all plots into 1
plot_names_clin_plus <- glue("{names(omic_dfs)}_sig_plot_clin_plus")
sig_plots_clin_plus <- mget(plot_names_clin_plus)

combined_sig_plot_clin_plus <- wrap_plots(sig_plots_clin_plus, 
                                               ncol = 2) + 
  plot_annotation(title = "Comparison of Marginal R² Across BMI Modeling Scores", 
                  theme = theme(plot.title = element_text(size = 18, 
                                                          face = "bold"))) &
                  theme(plot.margin = ggplot2::margin(20, 20, 20, 20, unit = "pt"))

print(combined_sig_plot_clin_plus)
output_file_sig_plot_clin_plus <- file.path(omic_out_dir, 
                                            "ANOVA_Marginal_R2_Comparison_sig_plot_clin_plus.png")

# Save the plot
ggsave(
  filename = output_file_sig_plot_clin_plus,
  plot = combined_sig_plot_clin_plus,
  width = 15,        # in inches (adjust as needed)
  height = 12,        # in inches (adjust as needed)
  dpi = 300          # high resolution
)
```


### Feature importances 


# Figure xxx : MERF feature importances

```{r echo=FALSE, fig.width = 6.5, fig.asp = 1.6, out.width="90%"}
merf_dfs_long <- list(Basic = basic, Clinical = meta, 
               Taxa = taxa, Micom = micom, 
               Pathways = pathway, Metabolites = metabo, 
               All = all)

merf_dfs_delta <- list(Basic = basic_md, Clinical = meta_md, 
                     Taxa = taxa_md, Micom = micom_md, 
                     Pathways = pathway_md, Metabolites = metabo_md, 
                     All = all_md)

ft_colors <- c(Clinical = "#960018", Taxa = "#8B3A3A", 
               Micom = "#996759", Pathways = "#D8A39D", 
               Metabolites  = "#C76374", All = "#C13427", 
               Basic = "#582F2B")

ft_colors_delta <- c(Clinical = "#960018", Taxa = "#8B3A3A", 
                     Micom = "#996759", Pathways = "#D8A39D", 
                     Metabolites  = "#C76374", All = "#C13427", 
                     Basic = "#582F2B")

# Combined feature sets
all_ft_dfs <- list(merf_lg = list(data = merf_dfs_long, 
                                  colors = ft_colors, 
                             label = "long", 
                             model_label = "MERF (Longitudinal BMI Prediction)",
                             x_ax_label = "Feature Importance"),
                   merf_delta = list(data = merf_dfs_delta, 
                                     colors = ft_colors_delta, 
                                label = "delta", 
                                model_label = "MERF (Change in BMI (Delta) Prediction)",
                                x_ax_label = "Feature Importance"))

merf_plots <- list()
for (type in names(all_ft_dfs)) {
  ft_set <- all_ft_dfs[[type]]$data
  color_map <- all_ft_dfs[[type]]$colors
  label <- all_ft_dfs[[type]]$label
  model_label <- all_ft_dfs[[type]]$model_label  # "MERF" or "GlmmLasso"
  x_ax_label <- all_ft_dfs[[type]]$x_ax_label
  
  output_dir <- file.path("omic_out_dir", paste0("ft_imp_", model_label, "_", label))
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  
  for (ft_name in names(ft_set)) {
    omic <- ft_set[[ft_name]]
    
    omic_parsed <- omic %>%
      mutate(Top_15_Feature_Importances = gsub("'", '"', Top_15_Feature_Importances)) %>%
      mutate(parsed = map(Top_15_Feature_Importances, fromJSON))
    
    omic_long <- omic_parsed %>%
      unnest(parsed) %>%
      dplyr::select(-Top_15_Feature_Importances) %>%
      filter(Feature != "time")
    
    avg_importance <- omic_long %>%
      group_by(Feature) %>%
      summarise(avg_importance = mean(Importance, na.rm = TRUE), .groups = "drop") %>%
      mutate(Feature = reorder(Feature, avg_importance)) %>%
      head(10)
    
    plot <- ggplot(avg_importance, aes(x = Feature, y = avg_importance)) +
      geom_col(fill = color_map[[ft_name]]) + #, width = 0.5
      labs(title = paste("", toupper(ft_name)),
        x = "Top 10 Model Features", 
        y = paste(" ", x_ax_label)) +
      theme_minimal(base_size = 14) +
      theme(legend.position = "none",
        plot.margin = ggplot2::margin(t = 1, r = 1, b = 1, l = 3, unit = "cm"),
        plot.title = element_text(hjust = 0, face = "bold", size = 16),
        axis.text.y = element_text(hjust = 1, face = "bold", size = 12),
        axis.text.x = element_text(face = "bold", size = 12),
        axis.title.x = element_text(margin = ggplot2::margin(0.5, 0, 0, 0, unit = "cm"), size = 14),
        axis.title.y = element_text(margin = ggplot2::margin(0, 0.5, 0, 0, unit = "cm"), size = 14),
        panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA)) +
      scale_y_continuous(limits = c(-0.05, 0.365), expand = expansion(mult = c(0, 0.05))) +
      #scale_x_continuous(limits = c(-0.1, 0.6)) +
      coord_flip(clip = "off")
    
    # Save to named R object
    #object_name <- paste0(ft_set, "_", ft_name, "_", label, "_plot")
    object_name <- paste0("plot_", type, "_", ft_name, "_", label)
    assign(object_name, plot, envir = .GlobalEnv)
    merf_plots[[object_name]] <- plot
    png_name <- file.path(omic_out_dir, 
                          paste0("merf_ft_imp/feature_importance_clin_plus", 
                                 ft_name, "_", label, ".png"))
    ggsave(filename = png_name, plot = plot, width = 9, height = 5, dpi = 300)
  }
}

merf_plots$plot_merf_lg_Clinical_long

```

## Save MERF feature plots 
```{r}
#for (i in seq_along(merf_plots)) {
#  ggsave(filename = file.path(omic_out_dir, 
#                         paste0("merf_ft_imp/merf_plot_clin_plus", i, ".png")),
#                         plot = merf_plots[[i]],
#                         width = 6, height = 4, dpi = 300)
#}

merf_long_plots <- merf_plots[c(2, 6, 7)]
combined_merf_long_plot <- wrap_plots(merf_long_plots, ncol = 3, nrow = 1) +
                           plot_annotation(title = "MERF longitudinal BMI Prediction Features",
                           theme = theme(plot.title = element_text(size = 18, face = "bold"))) &
                           theme(plot.margin = ggplot2::margin(8, 8, 8, 8, unit = "pt"))
ml_png_name <- file.path(omic_out_dir, 
                         paste0("merf_ft_imp/combined_merf_long_ft_clin_plus", ".png"))
ggsave(filename = ml_png_name,
       plot = combined_merf_long_plot, 
       width = 15, height = 5, dpi = 300)

merf_delta_plots <- merf_plots[c(9, 10, 13, 14)]
combined_merf_delta_plot <- wrap_plots(merf_delta_plots, nrow = 2, ncol = 2) +
                            plot_annotation(title = "MERF BMI Change Prediction Features",
                            theme = theme(plot.title = element_text(size = 18, face = "bold"))) &
                            theme(plot.margin = ggplot2::margin(8, 20, 8, 20, unit = "pt"))
md_png_name <- file.path(omic_out_dir, 
                         paste0("merf_ft_imp/combined_merf_delta_ft_clin_plus", ".png"))
ggsave(filename = md_png_name, 
       plot = combined_merf_delta_plot, 
       width = 10, height = 10, dpi = 300)

# Combine all MERF features plots 
merf_cow_plot_ft <- cowplot::plot_grid(
  combined_merf_long_plot,
  combined_merf_delta_plot,
  ncol = 1,
  nrow = 2,
  labels = c("A", "B"),
  label_size = 12,
  align = "hv",
  axis = "tblr",  # Align both top/bottom and left/right axes
  rel_widths = c(1, 1.35),
  scale = c(.95, .95))

merf_cow_plot_ft

ggsave(paste0(omic_out_dir, "merf_ft_imp/merf_ft_all_combined_clin.png"), merf_cow_plot_ft, 
       width = 40, height = 18, dpi = 300, bg = 'white')
```


```{r}

```











