---
title: "mirkat_for_metS"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(knitr, tidyverse, magrittr, lme4, lmerTest, GGally, corrplot, 
               Hmisc, kableExtra, dplyr, plyr, janitor, lubridate, survminer, 
               ggplot2, here, readr, dagitty, performance, see, car, sjPlot,
               RCurl, reshape2, summarytools, visdat, ggridges, grid, devtools,
               Boruta, car, effects, emmeans, flextable, ggfortify, ggpubr,vcd,
               Hmisc, knitr, MASS, knitr, lme4, MASS, mclogit, MuMIn, nlme,vip,
               ordinal, rms, robustbase, sjPlot, stringr, tibble, data.table)

load(file ="/Users/emily/projects/research/Stanislawski/BMI_risk_scores/microbiome_rs/data/Diversity/diversity_objects/BetaDiversity_DMs.RData")

meta <- read_csv(file = "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/meta_metS.csv")
```

# formatting just for baseline

```{r}
# BL Diversity files renaming 
# Unweighted 
un <- subset(un.unifrac, 
             substr(SampleID, nchar(SampleID) - 1, 
                    nchar(SampleID)) == "BL")
un$SampleID <- sub(".BL$", "", un$SampleID)
un_BL <- grep("BL$", names(un), value = TRUE)
un.bl <- subset(un, select = c("SampleID", un_BL))
colnames(un.bl) <- sub(".BL$", "", colnames(un.bl))

# Weighted
wt <- subset(wt.unifrac, 
             substr(SampleID, nchar(SampleID) - 1, 
                    nchar(SampleID)) == "BL")
wt$SampleID <- sub(".BL$", "", wt$SampleID)
wt_BL <- grep("BL$", names(wt), value = TRUE)
wt.bl <- subset(wt, select = c("SampleID", wt_BL))
colnames(wt.bl) <- sub(".BL$", "", colnames(wt.bl))

# Aitchison 
ait <- subset(aitchison,
             substr(SampleID, nchar(SampleID) - 1, 
                    nchar(SampleID)) == "BL")
ait$SampleID <- sub(".BL$", "", ait$SampleID)
ait_BL <- grep("BL$", names(ait), value = TRUE)
ait.bl <- subset(ait, select = c("SampleID", ait_BL))
colnames(ait.bl) <- sub(".BL$", "", colnames(ait.bl))

rm(aitchison, ait_BL, un, un_BL, wt, wt_BL)

## Meta Data ###
meta <- meta[!duplicated(meta$record_id), ]

# Extract the last three digits
ait.bl$SampleID <- sub(".*-(\\d{3})$", "\\1", ait.bl$SampleID)
un.bl$SampleID <- sub(".*-(\\d{3})$", "\\1", un.bl$SampleID)
wt.bl$SampleID <- sub(".*-(\\d{3})$", "\\1", wt.bl$SampleID)

intersect(meta$record_id, ait.bl$SampleID)
intersect(meta$record_id, un.bl$SampleID)
intersect(meta$record_id, wt.bl$SampleID)

meta_ait <- meta %>% subset(record_id %in% ait.bl$SampleID)
meta_un <- meta %>% subset(record_id %in% un.bl$SampleID)
meta_wt <- meta %>% subset(record_id %in% wt.bl$SampleID)

ait.bl <- ait.bl %>% subset(SampleID %in% meta_ait$record_id) %>% column_to_rownames("SampleID")
un.bl <- un.bl %>% subset(SampleID %in% meta_un$record_id) %>% column_to_rownames("SampleID")
wt.bl <- wt.bl %>% subset(SampleID %in% meta_wt$record_id) %>% column_to_rownames("SampleID")

ait.bl <- ait.bl[!duplicated(colnames(ait.bl)), ]
un.bl <- un.bl[!duplicated(colnames(un.bl)), ]
wt.bl <- wt.bl[!duplicated(colnames(wt.bl)), ]

meta_ait2 <- meta_ait %>% subset(record_id %in% rownames(ait.bl)) %>% unique()
meta_un2 <- meta_un %>% subset(record_id %in% rownames(un.bl)) %>% unique()
meta_wt2 <- meta_wt %>% subset(record_id %in% rownames(wt.bl)) %>% unique()
```


```{r}
# Change colnames to match record_is
colnames(ait.bl) <- substr(colnames(ait.bl), 
                           nchar(colnames(ait.bl)) - 2, 
                           nchar(colnames(ait.bl)))
meta_ait$record_id <- as.character(meta_ait$record_id)
### Make sure they match 
ait.bl <- ait.bl[c(meta_ait$record_id), c(meta_ait$record_id)]
table(rownames(ait.bl)==meta_ait$record_id)
table(colnames(ait.bl)==meta_ait$record_id)

# Change colnames to match record_is
colnames(wt.bl) <- substr(colnames(wt.bl), 
                           nchar(colnames(wt.bl)) - 2, 
                           nchar(colnames(wt.bl)))
meta_wt$record_id <- as.character(meta_ait$record_id)
### Make sure weighted matched 
wt.bl <- wt.bl[c(meta_wt$record_id), c(meta_wt$record_id)]
table(rownames(wt.bl)==meta_wt$subject_id)
table(colnames(wt.bl)==meta_wt$subject_id)

# Change colnames to match record_is
colnames(un.bl) <- substr(colnames(un.bl), 
                           nchar(colnames(un.bl)) - 2, 
                           nchar(colnames(un.bl)))
meta_un$record_id <- as.character(meta_un$record_id)

### Same for unweighted 
un.bl <- un.bl[c(meta_un$record_id), c(meta_un$record_id)]
table(rownames(un.bl)==meta_un$subject_id)
table(colnames(un.bl)==meta_un$subject_id)
```

# Run mirkat using AIT

```{r}
sex <- as.numeric(meta_ait$sex)
age <- as.numeric(meta_ait$age)
cohort <- as.numeric(meta_ait$cohort)
race <- as.numeric(meta_ait$race)

covar <- cbind(sex, age, cohort, race)

meta_ait$metS_num <- ifelse(meta_ait$metS == "healthy", 0,
                            ifelse(meta_ait$metS == "metS", 1, 2))
metS <- as.numeric(meta_ait$metS_num)
```


```{r}
library(MiRKAT)
K.un.bl= D2K(!is.na(as.matrix(un.bl)))
K.wt.bl= D2K(!is.na(as.matrix(wt.bl)))
K.ait.bl= D2K(!is.na(as.matrix(ait.bl)))
K.unifrac<- list(K.wt.bl, K.un.bl)


mirkat.ait <- MiRKAT(metS,
                     X = covar, 
                     Ks = K.ait.bl,
                     out_type ='D', 
                     returnKRV=T, 
                     returnR2=T, 
                     method= "permutation")

mirkat.wt <- MiRKAT(metS,
                     X = covar, 
                     Ks = K.wt.bl,
                     out_type ='D', 
                     returnKRV=T, 
                     returnR2=T, 
                     method= "permutation")

mirkat.un <- MiRKAT(metS,
                     X = covar, 
                     Ks = K.un.bl,
                     out_type ='D', 
                     returnKRV=T, 
                     returnR2=T, 
                     method= "permutation")

mirkat.ait[["p_values"]] # 0.56
mirkat.wt[["p_values"]] # 0.587
mirkat.un[["p_values"]] # 0.584
```

PCoA plots 

```{r}
#Perform PCA on the merged dataframe
library(FactoMineR)
pca_result <- PCA(ait.bl, scale.unit = TRUE, graph = FALSE)
colors <- c("healthy" = "#809bce", 
            "metS" = "#B2D3C2") #, "same" = "#7ec4cf", "NA" = "white")
library(factoextra)

pca_plot <- fviz_pca_ind(pca_result, 
                         geom = "point", 
                         col.ind = meta_ait$metS, 
                         palette = colors, 
                         addEllipses = TRUE, 
                         ellipse.type = "confidence",
                         ellipse.level=0.95,
                         legend.title = paste("healthy vs. metS"),
                         legend.position = "right")  +
            labs(x = "PC 1", y = "PC 2") +
            ggtitle("PCA Plot using Unweighted Unifrac")

# Customize legend and axis labels
pca_plot + theme(legend.title = element_text(size = 20),
                 legend.text = element_text(size = 15),
                 axis.title.x = element_text(size = 20),
                 axis.title.y = element_text(size = 20))
```

