---
title: "DRIFT2 - ANCOM"
author: "AW"
date: "2023-09-25"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

<br>
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = F, warning = F)
library(data.table)
library(tidyverse)
library(dplyr)
library(tidyr)
library(readxl)
# library(vegan)
# library(naniar)
library(magrittr)
library(RColorBrewer)
library(knitr)
# library(ggdendro)
library(reshape2)
# library(varhandle)
# library(exactRankTests)
library(phyloseq)
library(devtools)
#install_github("microbiome/microbiome")
library(microbiome)
#install.packages('upstartr')
# library(upstartr)
#install.packages('hrbrthemes')
# library(hrbrthemes)
#BiocManager::install("DESeq2")
# library(DESeq2)
library(ape)
library(Biostrings)
# BiocManager::install("ANCOMBC")
#install.packages("GUniFrac", repos = "https://cloud.r-project.org/")
library(GUniFrac)
#install.packages("LDM_6.0.tar.gz", repos = NULL, type = "source")
# library(LDM)
library(ecodist)
# BiocManager::install("mia")
# library(mia)
# devtools::install_github("jbisanz/qiime2R")
# devtools::install_github(repo = "aplantin/pldist")
# BiocManager::install("ComplexHeatmap")
# BiocManager::install("dada2")

#install.packages('MiRKAT') 
# library(MiRKAT)
#install.packages('tidyMicro') 
#devtools::install_github("CharlieCarpenter/tidyMicro")
#library(tidyMicro)
#devtools::install_github("microbiome/microbiome")
#BiocManager::install("MASS")
#install.packages("sorvi")
#remotes::install_github("mikemc/speedyseq")
# library(speedyseq)
# install.packages("microViz",
#   repos = c(davidbarnett = "https://david-barnett.r-universe.dev", getOption("repos")))
library(microViz)
library(DT)
library(Boruta)
library(caret)
library(randomForest)
```


## Data  
```{r}
#meta (currently removed individuals w/o secondary research and is only BL to 12m, will update to include 18m)
# meta <- fread(file='/Users/maggie/Documents/BIPM/K01/Code/Ashley_ANCOM_0923/meta_BLto12m_consent.csv')
load(file='/Users/maggie/Documents/BIPM/K01/Data/AnalysisData/meta_wide_out_2024_04_30.RData')

 load(file='/Users/maggie/Documents/BIPM/K01/Data/AnalysisData/Peta/crosswalk.RData')
load(file='/Users/maggie/Documents/BIPM/K01/Code/Ashley_ANCOM_0923/DRIFT2.Phylo.COUNT.0923.RData')

load(file='/Users/maggie/Documents/BIPM/K01/Data/AnalysisData/Peta/Genus_Sp_tables.RData')

```
## Predictors of outcomes


## baseline taxa as predictors

```{r , echo=F}     
zero.total<- colSums(genus.count==0)
## do we want to eliminate taxa base don baseline or total across all times?
prev.threhold<- 0.8*nrow(genus.count)
## has to be non-zero in at least 119 samples, ie present in 476

genus.sub<- genus.clr %>%
  dplyr::select(SampleID, one_of(names(zero.total[zero.total<prev.threhold])))
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Oscillospirales_f__Acutalibacteraceae_g__']<- 'f__Acutalibacteraceae_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Lachnospirales_f__Anaerotignaceae_g__']<- 'f__Anaerotignaceae_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Peptostreptococcales_f__Anaerovoracaceae_g__']<- 'f__Anaerovoracaceae_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Christensenellales_f__CAG-138_g__']<- 'f__CAG_138_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__TANB77_f__CAG-508_g__']<- 'f__CAG_508_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Christensenellales_f__CAG-74_g__']<- 'f__CAG_74_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_D_c__Bacilli_o__Erysipelotrichales_f__Coprobacillaceae_g__']<- 'f__Coprobacillaceae_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Lachnospirales_f__Lachnospiraceae_g__']<- 'f__Lachnospiraceae_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Oscillospirales_f__Oscillospiraceae_88309_g__']<- 'f__Oscillospiraceae_88309_g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Christensenellales_f___g__']<- 'o__Christensenellales_f___g__'
names(genus.sub)[names(genus.sub)=='d__Bacteria_p__Firmicutes_A_c__Clostridia_258483_o__Lachnospirales_f___g__']<- 'o__Lachnospirales_f___g__'

names(genus.sub)[names(genus.sub)=='g__CAG-274']<- 'g__CAG_274'
names(genus.sub)[names(genus.sub)=='g__CAG-127']<- 'g__CAG_127'
names(genus.sub)[names(genus.sub)=='g__CAG-317_146760']<- 'g__CAG_317_146760'

names(genus.sub)[names(genus.sub)=='g__CAG-269']<- 'g__CAG_269'
names(genus.sub)[names(genus.sub)=='g__CAG-41']<- 'g__CAG_41'
names(genus.sub)[names(genus.sub)=='g__CAG-1427']<- 'g__CAG_1427'
names(genus.sub)[names(genus.sub)=='g__CAG-83']<- 'g__CAG_83'
names(genus.sub)<- gsub("-","_",names(genus.sub))

meta.clr<-meta.wide2 %>%
  inner_join(
    dplyr::filter(crosswalk, timepoint=='BL')) %>%
  inner_join(genus.sub)
meta.wide2$wt
## we want to predict baseline BMI based on microbes - check outcome_BMI_fnl_BL as a predictor
meta.wide2$Intervention

covs.all<- c('age','male','outcome_wt_fnl_BL','Intervention', 'white', 'hispanic')
#covs.all<- c('age','male')
preds.all<- meta.clr %>%
  dplyr::select(one_of(covs.all), one_of(names(genus.sub)[-1]))

outcomes<-  meta.clr %>%
  dplyr::select(record_id, starts_with('change'), starts_with('pchange'), starts_with('wt_change'), starts_with('wt_pct'), -wt_pctchange_6m_3m, -wt_pctchange_12m_6m, -wt_pctchange_12m_3m)
outs<- names(outcomes)[-1]
```

```{r}
set.seed(111)
train_idx = createDataPartition(meta.clr$outcome_wt_fnl_BL, p = .7, list = F)
train = meta.clr[train_idx, ]
test = meta.clr[-train_idx, ]
control <- rfeControl(functions=rfFuncs, method="cv", number=3, repeats=10)

```

## do baseline features predict outcomes?

Relevant resources:

https://r-statistics.co/Variable-Selection-and-Importance-With-R.html

https://www.datacamp.com/tutorial/feature-selection-R-boruta


```{r}

fs.func<- function(yvar){
# yvar<- outs[1]
new.train<- train %>%
    dplyr::select(one_of(names(preds.all)), yvar)%>%
  dplyr::rename(y=yvar) %>%
    dplyr::filter(is.na(y)==F)
new.test<- test %>%
    dplyr::select(one_of(names(preds.all)), yvar)%>%
  dplyr::rename(y=yvar) %>%
    dplyr::filter(is.na(y)==F)
# run the Boruta algorithm
bor.res <- Boruta(y~., data=new.train, doTrace = 2, maxRuns=300)
# post.test<- predict(bor.res, new.test)

print(bor.res)
opt.vars1<- getSelectedAttributes(bor.res, withTentative = T)
opt.vars2<- getSelectedAttributes(bor.res, withTentative = F)

train.min1<- new.train %>%
    dplyr::select(one_of(opt.vars1), y)
train.min2<- new.train %>%
    dplyr::select(one_of(opt.vars2), y)

opt.rf1<- randomForest(y~., data=train.min1)
opt.rf2<- randomForest(y~., data=train.min2)

imp.vars1<- opt.rf1$importance %>%
  as.data.frame()%>%
  arrange(-IncNodePurity) %>%
  rownames_to_column('Variable')
imp.vars2<- opt.rf2$importance %>%
  as.data.frame()%>%
  arrange(-IncNodePurity) %>%
  rownames_to_column('Variable')

post.test1<- postResample(predict(opt.rf1, new.test), new.test$y)
post.test2<- postResample(predict(opt.rf2, new.test), new.test$y)

R2.1 <- opt.rf1$rsq[length(opt.rf1$rsq)]
rmse.1<- sqrt(opt.rf1$mse[length(opt.rf1$mse)])

R2.2 <- opt.rf2$rsq[length(opt.rf2$rsq)]
rmse.2<- sqrt(opt.rf2$mse[length(opt.rf2$mse)])

output.bor<- data.frame(y=yvar, Variables1 =length(opt.vars1), RMSE1=rmse.1,Rsquared1 =R2.1, 
                       Variables2 =length(opt.vars2), RMSE2=rmse.2,Rsquared2 =R2.2, 
                      
                       test.RMSE1=post.test1[1] ,
                        test.R21=post.test1[2] ,test.MAE1=post.test1[3] ,
                        test.RMSE2=post.test2[1] ,
                        test.R22=post.test2[2] ,test.MAE2=post.test2[3] ,
                       optvars1=paste(opt.vars1, collapse=', '),
                       optvars2=paste(opt.vars2, collapse=', ')
                        )


print(opt.rf1)
print(opt.rf2)
return(output.bor)
}
```



```{r}

output.fs<- fs.func(outs[1])
for(i in c(2:11)){
output.fs<- rbind(output.fs,fs.func(outs[i]))
print(i)
}
for(i in c(13:22)){
output.fs<- rbind(output.fs,fs.func(outs[i]))
print(i)
}

for(i in c(25:30)){
print(i)
output.fs<- rbind(output.fs,fs.func(outs[i]))
}

for(i in c(33:35)){
print(i)
output.fs<- rbind(output.fs,fs.func(outs[i]))
}

for(i in c(37:42)){
print(i)
output.fs<- rbind(output.fs,fs.func(outs[i]))
}
output.fs
# intersect(output.rfe$optvars)

table(output.fs$Variables1) ##25 have 160
table(output.fs$Variables2) ##25 have 160


for(i in c(12, 23,24,31,32,36)){
print(i)
output.fs<- rbind(output.fs,fs.func(outs[i]))
}
output.fs

# "change_ins_12m_bl"     "pchange_hba1c_6m_bl"   "pchange_homair_6m_bl"  "pchange_hba1c_12m_bl"  "pchange_homair_12m_bl" "pchange_wc_18m_bl"    

```

```{r}
summary(output.fs$test.R21*100)
summary(output.fs$test.R22*100)



```



## does change in features predict outcomes?


```{r}

fwrite(output.fs, file='/Users/maggie/Documents/BIPM/K01/Output/RFE/boruta.csv')
```



