---
title: "2.Taxa_Aim2_All_BL_testing"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(knitr, data.table, dplyr, tidyr,readxl,
               readr, car, LongituRF)
```

## Functions 
```{r}
read_data <- function(path, file) {
  read.csv(paste(path, file, sep = "/"))
}
# Make data long 
make_long <- function(wide_data) {
  wide_data %>% pivot_longer(
    cols = ends_with(c("BL", "6m", "12m")),  # Select columns that end with BL, 6m, or 12m
    names_to = c(".value", "time"),          # 2 new cols: .value for measurement types & time points
    names_pattern = "(.+)_(BL|6m|12m)") %>%  # Regex to separate measurement type and time point
  mutate(
    time = case_when(
      time == "BL" ~ 0,
      time == "6m" ~ 6,
      time == "12m" ~ 12,
      TRUE ~ as.numeric(time)  # In case there are any unexpected values
    ))
}

# Fix time 
create_t_column <- function(df) {
  df$t <- ifelse(df$timepoint == 'BL', 0,
                 ifelse(df$timepoint == '3m', 3,
                        ifelse(df$timepoint == '6m', 6,
                               ifelse(df$timepoint == '12m', 12, 18))))
}

# Run models 
train_all_models <- function(x, y, id_col, z, time_col, sto) {
  list(
    mert_model = MERT(X = X, Y = y, id = id, Z = z, time = time, sto = sto),
    reem_model = REEMtree(X = X, Y = y, id = id, Z = z, time = time, sto = sto),
    merf_model = MERF(X = X, Y = y, id = id, Z = z, time = time, sto = sto))
}

# Predict RF Long
pred_synth_data <- function(object, newdata, type = pred_type) {
  newdata_names <- list(
    X = c('X1', 'X2', 'X3', 'X4', 'X5', 'X6'),
    Z = c('Z1', 'Z2'),
    id = 'id',
    time = 'time'
  )
  
  LongituRF:::predict.longituRF(
    object,
    X    = newdata[newdata_names$X] |> as.matrix() |> unname(),
    Z    = newdata[newdata_names$Z] |> as.matrix() |> unname(),
    id   = newdata[[newdata_names$id]],  # vector 
    time = newdata[[newdata_names$time]]  # vector
  )
}

# Fix predictions 
# creates a data frame of predictions for all cases even if the predictions are for cases that weren’t observed in the data. The way we predict cases that are new is simply with the fixed effects.

fixed_prediction_function <- 
  function(object, X, id, Z, time, new_df, id_var_name, ...)
  {
  `%notin%` <- Negate(`%in%`)
  if("tidyverse" %notin% (.packages())){suppressMessages(library(tidyverse))}
  
  preds_existing <- 
    predict(
      object = object,
      X = X,
      id = id,
      Z = Z,
      time = time)
  
  temp <- 
    new_df %>% 
    #dplyr::filter({{id_var_name}} %notin% object$id) %>% 
    {print(nrow(.)); .} %>%
    mutate(predictions = predict(object = object$forest, newdata = .))
  
  final_df <- 
    new_df %>% 
    #dplyr::filter({{id_var_name}} %in% object$id) %>% 
    mutate(predictions = preds_existing) %>% 
    bind_rows(temp) %>% 
    select(all_samples, predictions)
  return(final_df)
}
```

## Load Taxa Data 
```{r}
t_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/taxa/aim2_transformed/"
tax_test <- read_data(t_dir, "genus/aim2_clr_testing.csv")
tax_train <- read_data(t_dir, "genus/aim2_clr_training.csv")
tax_full <- read_data(t_dir, "genus/clr_taxa_all.csv")
# Load Meta data 
m1_dir <- "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/clinical/transformed/aim2"
test <- read_data(m1_dir, "a2_test_samples_standard_clinical.csv")
train <- read_data(m1_dir, "a2_train_samples_standard_clinical.csv")
full <- read_data(m1_dir, "a2_meta_Transformed_standard_clinical.csv")
full_raw <- read_data(m1_dir, "a2_meta_not_Transformed_standard_clinical.csv")
```

# Edit Taxa Input data 
```{r}
# FULL
# change names of tax full
tax_full_t <- tax_full %>%
  separate(X, remove=FALSE, sep="\\.", into=c('character_id','timepoint'))
# make time numeric
tax_full_t$t <- create_t_column(tax_full_t) %>% as.character()
# Make a new var to match meta 
tax_full_t <- tax_full_t %>%
  mutate(x_t = paste(character_id, t, sep = "."))

tax <- tax_full_t %>% 
       filter(!t == 3) %>% 
       filter(!t == 18) %>% 
       dplyr::select(-c(t, timepoint, character_id, X))

# TAXA TRAINING 
# change names of tax train
train_t <- tax_train %>%
  separate(X, remove=FALSE, sep="\\.", 
           into=c('character_id','timepoint'))

# make time numeric
train_t$t  <- create_t_column(train_t) %>% as.character()
# Make a new var to match meta 
train_t <- train_t %>%
  mutate(x_t = paste(character_id, t, sep = ".")) %>% 
       filter(!t == 3) %>% 
       filter(!t == 18) # %>% 
       #dplyr::select(-c(t, timepoint, character_id, X))

# TAXA TESTING
# change names of tax test 
test_t <- tax_test %>%
  separate(X, remove=FALSE, sep="\\.", 
           into=c('character_id','timepoint'))

# make time numeric
test_t$t  <- create_t_column(test_t) %>% as.character()

test_t <- test_t %>%
  mutate(x_t = paste(character_id, t, sep = ".")) %>% 
       filter(!t == 3) %>% 
       filter(!t == 18) 

rm(tax_test, tax_train)
rm(tax, tax_full)
```

## Make meta long 
```{r}
# Make meta long full
full_long <- make_long(full_raw) %>%
  mutate(x_t = paste(subject_id, time, sep = "."))

# Make meta long full for meta training 
train_long <- make_long(train) %>%
  mutate(x_t = paste(subject_id, time, sep = "."))

# Make meta long for meta testing
test_long <- make_long(test) %>%
  mutate(x_t = paste(subject_id, time, sep = "."))

rm(test, train, full_raw, full)
```

### Merge Meta and Taxa Training and Testing sets 

```{r}
# select meta
test_meta <- test_long %>% dplyr::select(c(x_t, outcome_BMI_fnl))
train_meta <- train_long %>% dplyr::select(c(x_t, outcome_BMI_fnl))
# # Merge 
train_tax <- merge(train_t, 
                   train_meta, 
                   by = "x_t") %>% 
                   dplyr::select(-x_t, -X, -character_id, -timepoint)

test_tax <- merge(test_t, 
                  test_meta, 
                  by = "x_t") %>% 
                  dplyr::select(-x_t, -X, -character_id, -timepoint)

full <- merge(tax_full_t, full_long, by = "x_t") %>% 
        dplyr::select(-X.y, -X.x, -x_t, -randomized_group, -cohort_number, -record_id, 
                      -subject_id, -character_id, -cohort_number, -age, 
                      -race, -sex,  -time, -timepoint,
                      -HOMA_IR, -Insulin_endo, -HDL_Total_Direct_lipid, -Glucose,
                      -LDL_Calculated, -Triglyceride_lipid)

rm(train_meta, test_meta, test_t, train_t, test_long, train_long, full_long, tax_full_t)
```

### Remove NAs and filter for time 
```{r}
#full_no_na <- full %>% filter(!record_id %in% na_record_ids)
full_no_na <- na.omit(full)
test_tax_no_na <-na.omit(test_tax)
train_tax_no_na <- na.omit(train_tax)

demo_train <- full_no_na %>% filter(t < 12)
demo_test <- full_no_na %>% filter(t == 12)

# Train
# for all in training, put all TP - some only have BL - mark these as testing people. 

# Test
# for all in testing set, only keep BL - 


```

### Keep those with 3 time entries 
```{r}
## this tells us who was here for 3 years
three_time_ids <- 
  train_tax_no_na %>% 
  count(all_samples) %>% 
  arrange(n) %>% 
  dplyr::filter(n == 3) %>% 
  pull(all_samples)

train_time_3 <- 
  train_tax_no_na %>% 
  dplyr::filter(all_samples %in% three_time_ids) %>% 
  pull(t)

train_tax_3 <- 
  train_tax_no_na %>% 
  filter(all_samples %in% three_time_ids) %>% 
  select(-t) %>% 
  #mutate_if(Negate(is.factor), scale) %>% 
  mutate(t = train_time_3)
```

## Start Long RF
```{r}
train_set <- demo_train
# the predictors you want 
X <- train_set %>% 
  dplyr::select(-t, -outcome_BMI_fnl, -all_samples) 

list_dat <- 
  list(X = X, # predictors, BL and 6m
    Y = as.numeric(pull(train_set, outcome_BMI_fnl)), # outcome
    id = as.vector(pull(train_set, all_samples)), # id variables for each unique 
    Z = as.matrix(rep(1, nrow(train_set))),  # random effects (I'm using only a random intercept)
    time = as.numeric(pull(train_set, t)))
```

# MERT, REEMtree & MERF
```{r}
mert1 <- 
  MERT(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = list_dat$Z,
    time = list_dat$time,
    sto = 'OrnUhl', # Ornstein–Uhlenbeck
    #iter = 100, 
    #delta = 0.001)
  )

# REEMtree
reemtree1 <- 
  REEMtree(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = list_dat$Z,
    time = list_dat$time,
    sto = 'OrnUhl',
    #iter = 100,
    #delta = 0.001
  )
```

```{r}
# MERF
Z_matrix <- as.matrix(list_dat$Z)
dim(Z_matrix)  # Should print [1] 206 1

merf1 <- 
  MERF(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = Z_matrix,
    time = list_dat$time,
    sto = 'OrnUhl',
    iter = 100,
    delta = 0.001,
    mtry = ceiling(ncol(data.frame(list_dat$X))/3),
    ntree = 500
  )
```
debug merf ecp - ignore 
```{r}
# Add this diagnostic code right before running MERF
debug_merf <- function(X, Y, id, Z, time) {
    # Initial setup from MERF function
    q <- dim(Z)[2]
    nind <- length(unique(id))
    btilde <- matrix(0, nind, q)
    # Print dimensions
    print("Initial dimensions:")
    print(paste("Z dimensions:", dim(Z)))
    print(paste("btilde dimensions:", dim(btilde)))
    print(paste("q:", q))
    print(paste("nind:", nind))
    # Check first individual
    k <- 1
    indiv <- which(id == unique(id)[k])
    print("First individual check:")
    print(paste("indiv length:", length(indiv)))
    print(paste("Z[indiv,] dimensions:", dim(Z[indiv, , drop=FALSE])))
    print(paste("btilde[k,] dimensions:", length(btilde[k,])))
}
# Run diagnostics
debug_merf(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = Z_matrix,
    time = list_dat$time
)

merf1 <- MERF(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = as.matrix(Z_matrix),    # Extra ensure it's a matrix
    time = as.numeric(list_dat$time),  # Ensure time is numeric
    sto = 'exp',
    iter = 100,
    delta = 0.001,
    mtry = ceiling(ncol(data.frame(list_dat$X))/3),
    ntree = 500
)
```

```{r}
# First, let's create a modified version of MERF that adds some debugging
MERF_debug <- function(X, Y, id, Z, time, sto, iter=100, mtry, ntree=500, delta=0.001) {
    # Initialize as before
    q <- dim(Z)[2]
    nind <- length(unique(id))
    btilde <- matrix(0, nind, q)
    sigmahat <- 1
    Btilde <- diag(rep(1,q))
    epsilonhat <- rep(0, length(Y))
    id_btilde <- unique(id)
    
    # Add debugging for first iteration
    k <- 1
    indiv <- which(id == unique(id)[k])
    
    # Print detailed information
    print("Debugging information:")
    print(paste("Z class:", class(Z)))
    print(paste("Z dimensions:", paste(dim(Z), collapse="x")))
    print(paste("btilde class:", class(btilde)))
    print(paste("btilde dimensions:", paste(dim(btilde), collapse="x")))
    print("First multiplication attempt:")
    print(paste("Z[indiv,] dimensions:", paste(dim(Z[indiv, , drop=FALSE]), collapse="x")))
    print(paste("btilde[k,] dimensions:", paste(dim(matrix(btilde[k,], ncol=q)), collapse="x")))
    
    # Try explicit matrix multiplication
    Z_sub <- Z[indiv, , drop=FALSE]
    b_sub <- matrix(btilde[k,], ncol=q)
    print("Attempting multiplication with explicit matrices:")
    print(Z_sub %*% t(b_sub))
    
    # Return NULL just for testing
    return(NULL)
}

# Try the debug version
result <- MERF_debug(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = as.matrix(Z_matrix),
    time = as.numeric(list_dat$time),
    sto = 'exp',
    iter = 100,
    mtry = ceiling(ncol(data.frame(list_dat$X))/3),
    ntree = 500
)
```

```{r}
merf1 <- MERF_editted(
    X = data.frame(list_dat$X),
    Y = list_dat$Y,
    id = list_dat$id,
    Z = as.matrix(Z_matrix),
    time = as.numeric(list_dat$time),
    sto = 'exp',
    iter = 100,
    delta = 0.001,
    mtry = ceiling(ncol(data.frame(list_dat$X))/3),
    ntree = 500
)
```


### Prep test data

```{r}
X_test <- 
  demo_test %>% 
  dplyr::filter(all_samples %in% mert1$id) %>% 
  dplyr::select(-t, -outcome_BMI_fnl, -all_samples)

list_test <- 
  list(X = X_test,
    Y = as.numeric(demo_test %>% 
                     dplyr::filter(all_samples %in% merf1$id) %>% 
                     pull(outcome_BMI_fnl)),
    id = as.numeric(demo_test %>% 
                      dplyr::filter(all_samples %in% merf1$id) %>% 
                      pull(all_samples)),
    Z = as.matrix(rep(1, nrow(demo_test))), 
    time = demo_test %>% 
           dplyr::filter(all_samples %in% merf1$id) %>% 
           pull(t))
```

# How well do the models perform when predicting

### First using MERT 
```{r}
pred_mert1 <- predict(mert1, 
                     X=list_test$X,
                     Z=list_test$Z,
                     id=list_test$id, 
                     time=as.numeric(list_test$time)) # %>% as.data.frame()

cor(pred_mert1, list_test$Y)^2
plot(pred_mert1, list_test$Y)
```

# Using REEM
```{r}
pred_reem1 <- predict(reemtree1, 
                     X=list_test$X,
                     Z=list_test$Z,
                     id=list_test$id, 
                     time=as.numeric(list_test$time)) # %>% as.data.frame()

cor(pred_reem1, list_test$Y)^2
```

# Using MERF
```{r}
pred_merf1 <- predict(merf1, 
                     X=list_test$X,
                     Z=list_test$Z,
                     id=list_test$id, 
                     time=as.numeric(list_test$time)) # %>% as.data.frame()

cor(pred_merf1, list_test$Y)^2
```





