---
title: "metS_proportions"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(knitr,data.table,dplyr,tidyr,tableone,kableExtra,readr)
```

read in meta 

```{r}
# Getting weight changes 
load("/Users/emily/projects/research/Stanislawski/BMI_risk_scores/data/correct_meta_files/meta_wide.RData")

m1 <- meta.wide %>% 
      dplyr::select(c("record_id", "sex", "wc_average_BL", 
                      "avg_diastolic_BL", "avg_systolic_BL"))
```

more clinicals

```{r}
# Extra labs
all_labs_data_h <- read_csv("/Users/emily/projects/research/Stanislawski/python/scripts/data/all_labs_data_h.csv")
screen_labs_data <- all_labs_data_h %>% dplyr::filter(week == -1)
base_labs_data <- all_labs_data_h %>% dplyr::filter(week == 0)

m2 <- base_labs_data %>% 
      dplyr::select(c("record_id","Glucose", "Glucose_1", "HDL_Total_Direct_lipid",
                      "Triglyceride_lipid", "Triglyceride_lipid_1"))
```

one BL dataframe with all of them (Glc, TGs, WC, BP, HDL)

```{r}
metS <- merge(m1, m2, by = "record_id")
metS_male <- metS %>% dplyr::filter(metS$sex == "1")
metS_female <- metS %>% dplyr::filter(metS$sex == "0")
```

make if else statements for metS

```{r}
metS$met_gluc <- ifelse(metS$Glucose >= 100, 1, 0)
metS$met_tg <- ifelse(metS$Triglyceride_lipid >= 150, 1, 0)
metS$met_bp <- ifelse(metS$avg_systolic_BL >= 130, 1,
                      ifelse(metS$avg_diastolic_BL >= 85, 1, 0))

# Sex diff
metS_female$met_hdl <- ifelse(metS_female$HDL_Total_Direct_lipid <= 50, 1, 0)
metS_male$met_hdl <- ifelse(metS_male$HDL_Total_Direct_lipid <= 40, 1, 0)

metS_female$met_wc <- ifelse(metS_female$wc_average_BL >= 89, 1, 0)
metS_male$met_wc <- ifelse(metS_male$wc_average_BL >= 102, 1, 0)

# merge
mf <- metS_female %>% dplyr::select(record_id, met_hdl, met_wc)
mm <- metS_male %>% dplyr::select(record_id, met_hdl, met_wc)
mfm <- rbind(mf, mm)
mmm <- merge(mfm, metS, by = "record_id")
```

met S criteria >3 

```{r}
# Calculate the sum of the specified columns and create the new variable
m4met <- mmm %>%dplyr::select(c("record_id", "met_hdl", "met_wc", "met_gluc", 
                                "met_tg", "met_bp")) %>% 
            column_to_rownames("record_id")
m4met$metS <- ifelse(rowSums(m4met[c("met_hdl", "met_wc", "met_gluc", 
                                         "met_tg", "met_bp")]) >= 3, 
                                         "metS", "healthy")

met <- m4met %>% rownames_to_column("record_id")
```

merge back to the rest of the meta 

```{r}
meta <- merge(met, meta.wide, by = "record_id")
#write.csv(meta, file = "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/meta_metS.csv", row.names = FALSE)
```

summary 

```{r}
ggplot(meta, aes(outcome_BMI_fnl_BL, wc_average_BL)) + geom_point()
```

```{r}
meta %>% ggplot(aes(x = metS, y = wt_pctchange_12m_bl)) +
  geom_boxplot(aes(color = metS), width = 0.8, outliers = FALSE) + 
  #xlab("Race and/or Ethnicity") +
  #ylab("Child Opportunity Index Score") + 
  facet_grid("sex") +
  scale_fill_manual(values = c("#809bce", "#B2D3C2", "#7ec4cf", "#a6cee3", 
                               "#1f78b4", "#b2df8a", "#39a46c"))
```

Table one 

```{r}
# which vars to include 
descrip_vars <- c("metS","sex","age","race",
                  "wc_average_BL","avg_diastolic_BL","avg_systolic_BL",
                  "clin.sig.wtloss.final")

desc_labels <- c("metS","sex","age","race",
                  "waist_circ_BL","BP_diastolic_BL","BP_systolic_BL",
                  "clin.sig.wtloss.final")

des_cat_vars <- c("sex","race","metS","clin.sig.wtloss.final")

descrip_table <- dplyr::select(meta, one_of(descrip_vars))

labelled::var_label(descrip_table) <- desc_labels
descriptive_T1 <- CreateTableOne(vars = descrip_vars, 
                                   data = descrip_table, 
                                   factorVars = des_cat_vars, 
                                   strata = "metS",
                                   includeNA=T,
                                   addOverall = T,
                                   test = TRUE,
                                   testApprox = chisq.test,
                                   testNormal = oneway.test,
                                   argsNormal = list(var.equal = TRUE),
                                   testNonNormal = kruskal.test)
#kable(summary(descriptive_T1))
d_T1 <- print(descriptive_T1,
               catDigits = 1, 
               contDigits = 1, 
               varLabels = T,
               exact = "stage", 
               quote = FALSE, 
               noSpaces = TRUE, printToggle = FALSE)

## Save to html
d_T1 <- d_T1 %>% 
     kable(caption = "Baseline Characteristics") %>%
     kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)
#write.csv(d_T1, 
#          file = "/Users/emily/projects/research/ADOR/CHLA_clean/outputs/tables/Table1_April12.html")
d_T1
```

boxplot

```{r}
ggplot(meta, aes(x = metS, y = wt_pctchange_12m_bl, fill = sex)) +
  geom_boxplot(alpha = 0.6, position = position_dodge(width = 0.9)) +
  scale_fill_manual(values = c("#809bce", "#B2D3C2", "#7ec4cf", "#a6cee3", 
                               "#1f78b4", "#b2df8a", "#39a46c"), 
                    name = "Sex") +
  labs(x = "MetS or Healthy", y = "% weight change") +
  #scale_y_continuous(sec.axis = dup_axis(label = NULL,
  #                                       name = NULL),
  #                   expand = expansion(mult = c(0, 0)),
  #                   breaks = pretty(c(40,130), n = 10),
  #                   limits = c(40,130)) +
  theme(axis.title.x = element_text(margin = margin(t = 20), 
                                    hjust = 0.5,
                                    size = 13),  
        axis.title.y = element_text(margin = margin(r = 20), 
                                    hjust = 0.5,
                                    size = 12),
        axis.text.x = element_text(size = 10),  
        axis.text.y = element_text(size = 10),
    #panel.grid.major = element_line(color = "black", size = 0.5),  
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line.x = element_line(color = "black"), 
    axis.line.y = element_line(color = "black"), 
    axis.line.y.right = element_blank(),
        legend.title = element_text(size = 12),
        plot.margin = margin(1, 0, 1, 0.5, "cm"),
        legend.position = "right")
```
```{r}
just_met <- meta %>% dplyr::select(c("record_id", "metS"))
long <- merge(just_met, all_labs_data_h, by = "record_id")


```

