---
title: "1.prep_meta_lasso"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(dplyr, glmnet, rROC, PredictABEL, nricens, caret,
               tidyr, ggplot2, randomForest)
pacman::p_load(knitr, tidyverse, plyr, here, readr, gridExtra,
               summarytools, data.table, corrplot, devtools, tibble, grid, 
               jtools, broom, patchwork, phyloseq, microbiome, ISLR,
               MicrobiomeStat, ANCOMBC, ape, vegan, zCompositions, janitor)
```

### Example Lasso 

```{r}
data("swiss")
x_vars <- model.matrix(Fertility~. , swiss)[,-1]
y_var <- swiss$Fertility
lambda_seq <- 10^seq(2, -2, by = -.1)

# Splitting the data into test and train
# Assuming 'df' is your dataframe and 'response_variable' is your target variable
set.seed(123)  # Set seed for reproducibility
train_index <- createDataPartition(swiss$Fertility, p = 0.8, list = FALSE)
train <- swiss[train_index, ]
test <- swiss[-train_index, ]

x_vars_train <- model.matrix(Fertility~. , train)[,-1]
y_var_train <- train$Fertility
x_vars_test <- model.matrix(Fertility~. , test)[,-1]
y_var_test <- test$Fertility

cv_output <- cv.glmnet(x_vars_train, y_var_train,
                       alpha = 1, lambda = lambda_seq, 
                       nfolds = 5)

# identifying best lamda
best_lam <- cv_output$lambda.min
best_lam

# Rebuilding the model with best lamda value identified
lasso_best <- glmnet(x_vars_train, 
                     y_var_train, 
                     alpha = 1, 
                     lambda = best_lam)

coef(lasso_best)[,1]!=0

# See what the model predicted
pred <- predict(lasso_best, 
                s = best_lam, 
                newx = x_vars_test)

# Bind predicted and actual
final <- cbind(y_var_test, pred) %>% 
  as.data.frame() %>% 
  rename("Actual" = "y_var_test", 
         "Pred" = "s1")
head(final)

# TESTING R Square
actual <- final$Actual
preds <- final$Pred
rss <- sum((preds - actual) ^ 2)
tss <- sum((actual - mean(actual)) ^ 2)
rsq <- 1 - rss/tss
rsq # model explains 56.05% of the variance in the dependent variable
```

# My data

```{r}
# Phyloseq Object
load("~/projects/research/Stanislawski/BMI_risk_scores/microbiome_rs/data/PhyloseqObj.RData")
# Ancom results 
load("~/projects/research/Stanislawski/BMI_risk_scores/microbiome_rs/Code_for_ANCOM/emily_acom_outputs/ancom_sig_bmi.04.15.RData")
# Phyloseq species object
load("/Users/emily/projects/research/Stanislawski/BMI_risk_scores/microbiome_rs/data/Genus_Sp_tables.RData")
#rm(drift.phy.count.r21116, drift.phy.ra, genus.clr, genus.count, genus.ra)
```

### Make training and testing 

```{r}
sp.data <- sp.clr
sample_names <- sp.data$SampleID
baseline_samples <- sp.data$SampleID[grep("\\.BL$", sample_names)]
BL_clr <- sp.data %>% filter(SampleID %in% baseline_samples)

# Make training and testing to match the samples in training and testing of ANCOMBC
training_sample_names <- sample_names(train_bl)
testing_sample_names <- sample_names(test_bl)

# Filter rows in BL_clr that match training and testing samples 
BL_clr_training <- BL_clr %>% filter(SampleID %in% training_sample_names)
BL_clr_testing <- BL_clr %>% filter(SampleID %in% testing_sample_names)

# Merge training set to meta data
BL_met_train <- merge(meta.long, BL_clr_training, by = "SampleID",
                        all.x = FALSE, all.y = TRUE)

# Merge testing set to meta data
BL_met_test <- merge(meta.long, BL_clr_testing, by = "SampleID",
                        all.x = FALSE, all.y = TRUE)

rm(meta.long, BL_clr_testing, BL_clr_training,
   train_bl, test_bl, train_long)
```

### Lasso on Taxa 

```{r}
BL_BMI_train <- BL_met_train$B_outcome_BMI_fnl %>% na.omit()
predictors_marix <- data.matrix(BL_met_train[, -c('timepoint','Week','income',
                      'B_outcome_wt_fnl', 'B_outcome_BMI_fnl','SampleID',
                      'subject_id','diet_grp','Intervention','time','timepoint', 
                      'Week', 'B_outcome_wt_fnl','ethnicity','education',
                      'outcome_BMI_fnl', 'IMF_diet_adh_total',
                      'DCR_diet_adh_total')]) %>% na.omit()

# Best lambda 
sp_lamb <- cv.glmnet(x = predictors_marix, y = BL_BMI_train, 
                         alpha = 1, family='gaussian')
hist(sp_lamb$lambda)

# Model GLM
BL_BMI_glm <- glmnet(x = predictors_marix, y = BL_BMI_train, 
                               family = 'gaussian', 
                               lambda =  1.5)

length(coef(BL_BMI_glm)[,1]!=0)
# Identify the coefficients that are non-zero in the fitted LASSO model
coef.tokeep.001<- coef(BL_BMI_glm)[,1]!=0
#names(coef.tokeep.001[BL_BMI_glm==T])[-1]
coef_BL_BMI_glm <- coef(BL_BMI_glm)
coef_to_keep <- coef_BL_BMI_glm != 0
```

### Predicting using the model

```{r}

```

