---
title: "6.genetic_risk_score"
author: "Emily Yeo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(knitr, data.table, dplyr, tidyr, tableone, kableExtra, readxl,
               readr, car, RColorBrewer, gridExtra, mlbench, earth, ggplot2, 
               AppliedPredictiveModeling, caret, reshape2, corrplot, stringr,
               summarytools, grid, mice, plyr, mlmRev, cowplot, compositions,
               jtools, broom, patchwork, phyloseq, microbiome, glmnet, ISLR,
               MicrobiomeStat, ANCOMBC, ape, vegan, zCompositions, janitor)
```

About the file genetic risk scores:
https://emilyyeo.notion.site/Processing-New-Genomic-Data-08de0484448946e586790c1440080d4d

Code for bigsnpr:
/Users/emily/projects/research/Stanislawski/BMI_risk_scores/full_cohort_pulling_snps/bigsnpr/Merged_scores_BMI_analysis.Rmd

```{r message=FALSE, warning=FALSE}
meta_o <- read_csv("/Users/emily/projects/research/Stanislawski/BMI_risk_scores/full_cohort_pulling_snps/bigsnpr/made_scores/merge_meta_methyl.csv")

meta <- meta_o %>%
  dplyr::select(c(subject_id, raw_score, old_or_new, predicted_BL_BMI, 
                  differences_BL_BMI, diff_BMI_quartile, diff_BMI_std, 
                  mrs.wt, mrs.std.wt)) %>%
  dplyr::rename(bmi_prs = raw_score,
                methyl_bmi_rs = mrs.wt,
                methyl_bmi_rs_standardized = mrs.std.wt)
```

look at scores

```{r}
hist(meta$bmi_prs)
```

# split into training and testing that matches meta data split 

```{r}
# Testing and training meta data 
train_Transformed  <- fread("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/clinical/transformed/aim1/train_samples_standard_clinical.csv")

test_Transformed  <- fread("/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/clinical/transformed/aim1/test_samples_standard_clinical.csv")
```


```{r}
# Make training & testing to match the samples in training and testing meta
training_sample_names <- train_Transformed$subject_id
testing_sample_names <- test_Transformed$subject_id

# AIM1 data 
prs_samples <- meta$subject_id
BL_genetic_risk_testing <- meta %>% filter(prs_samples %in% testing_sample_names)
BL_genetic_risk_training <- meta %>% filter(prs_samples %in% training_sample_names)
```

# Write files

```{r}
# write.csv(BL_genetic_risk_training, "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/genetic/genetic_risk_training.csv")
# write.csv(BL_genetic_risk_testing, "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/genetic/genetic_risk_testing.csv")
# write.csv(meta, "/Users/emily/projects/research/Stanislawski/comps/mutli-omic-predictions/data/genetic/genetic_risk.csv")

```

